---
project:
  type: website
  output-dir: docs

website:
  navbar:
    right: 
      - text: Inicio
        file: index.qmd
      - text: Análisis descriptivo
        file: descriptivo.qmd
      - text: Evaluación de hipótesis
        file: hipotesis.qmd
      - text: Modelos
        file: modelos.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    code-copy: true

language: _language.yml
---
