project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    # - "!descriptivo.qmd"
    # - "!hipotesis.qmd"
    # - "!modelos.qmd"
    # - "!ipc.qmd"

website:
  navbar:
  # sidebar: true
    right: 
      - text: Inicio
        file: index.qmd
      - text: Análisis descriptivo
        file: descriptivo.qmd
      - text: Evaluación de hipótesis
        file: hipotesis.qmd
      - text: Modelos
        file: modelos.qmd
      - text: IMC
        file: ipc.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4
    code-copy: true
    search: true
    section-divs: true
    page-layout: full

language: _language.yml
