project:
  type: website
  output-dir: docs

website:
  navbar:
  # sidebar: true
    right: 
      - text: Inicio
        file: index.qmd
      - text: Análisis descriptivo
        file: descriptivo.qmd
      - text: Evaluación de hipótesis
        file: hipotesis.qmd
      - text: Modelos
        file: modelos.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true
    search: true
    section-divs: true
    page-layout: article

language: _language.yml
