<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>modelos---copia</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "Ninguna coincidencia",
    "search-matching-documents-text": "coincidencias",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target="">
 <span class="menu-text">Inicio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./descriptivo.html" rel="" target="">
 <span class="menu-text">Análisis descriptivo</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./hipotesis.html" rel="" target="">
 <span class="menu-text">Evaluación de hipótesis</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./modelos.html" rel="" target="">
 <span class="menu-text">Modelos</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenido</h2>
   
  <ul>
  <li><a href="#modelos" id="toc-modelos" class="nav-link active" data-scroll-target="#modelos">Modelos</a>
  <ul>
  <li><a href="#modelo-normal" id="toc-modelo-normal" class="nav-link" data-scroll-target="#modelo-normal">Modelo Normal</a>
  <ul class="collapse">
  <li><a href="#lrt-antropómetro" id="toc-lrt-antropómetro" class="nav-link" data-scroll-target="#lrt-antropómetro">LRT Antropómetro</a></li>
  <li><a href="#lrt-cinta-métrica" id="toc-lrt-cinta-métrica" class="nav-link" data-scroll-target="#lrt-cinta-métrica">LRT cinta métrica</a></li>
  <li><a href="#lrm-pierna-estirada" id="toc-lrm-pierna-estirada" class="nav-link" data-scroll-target="#lrm-pierna-estirada">LRM pierna estirada</a></li>
  <li><a href="#lrm-pierna-a-90" id="toc-lrm-pierna-a-90" class="nav-link" data-scroll-target="#lrm-pierna-a-90">LRM pierna a 90°</a></li>
  <li><a href="#resúmen-modelos-normal" id="toc-resúmen-modelos-normal" class="nav-link" data-scroll-target="#resúmen-modelos-normal">Resúmen modelos Normal</a></li>
  </ul></li>
  <li><a href="#modelo-lasso" id="toc-modelo-lasso" class="nav-link" data-scroll-target="#modelo-lasso">Modelo Lasso</a>
  <ul class="collapse">
  <li><a href="#lrt-antropómetro-1" id="toc-lrt-antropómetro-1" class="nav-link" data-scroll-target="#lrt-antropómetro-1">LRT Antropómetro</a></li>
  <li><a href="#lrt-cinta-métrica-1" id="toc-lrt-cinta-métrica-1" class="nav-link" data-scroll-target="#lrt-cinta-métrica-1">LRT cinta métrica</a></li>
  <li><a href="#lrm-pierna-estirada-1" id="toc-lrm-pierna-estirada-1" class="nav-link" data-scroll-target="#lrm-pierna-estirada-1">LRM pierna estirada</a></li>
  <li><a href="#lrm-pierna-a-90-1" id="toc-lrm-pierna-a-90-1" class="nav-link" data-scroll-target="#lrm-pierna-a-90-1">LRM pierna a 90°</a></li>
  <li><a href="#resumen-modelos-lasso" id="toc-resumen-modelos-lasso" class="nav-link" data-scroll-target="#resumen-modelos-lasso">Resumen modelos LASSO</a></li>
  </ul></li>
  <li><a href="#modelo-gamma" id="toc-modelo-gamma" class="nav-link" data-scroll-target="#modelo-gamma">Modelo Gamma</a>
  <ul class="collapse">
  <li><a href="#lrt-antropómetro-2" id="toc-lrt-antropómetro-2" class="nav-link" data-scroll-target="#lrt-antropómetro-2">LRT Antropómetro</a></li>
  <li><a href="#lrt-cinta-métrica-2" id="toc-lrt-cinta-métrica-2" class="nav-link" data-scroll-target="#lrt-cinta-métrica-2">LRT cinta métrica</a></li>
  <li><a href="#lrm-pierna-estirada-2" id="toc-lrm-pierna-estirada-2" class="nav-link" data-scroll-target="#lrm-pierna-estirada-2">LRM pierna estirada</a></li>
  <li><a href="#lrm-pierna-90" id="toc-lrm-pierna-90" class="nav-link" data-scroll-target="#lrm-pierna-90">LRM pierna 90°</a></li>
  <li><a href="#resumen-modelos-gamma" id="toc-resumen-modelos-gamma" class="nav-link" data-scroll-target="#resumen-modelos-gamma">Resumen modelos Gamma</a></li>
  </ul></li>
  <li><a href="#propuesta-nuevas-fórmulas" id="toc-propuesta-nuevas-fórmulas" class="nav-link" data-scroll-target="#propuesta-nuevas-fórmulas">Propuesta: Nuevas fórmulas</a></li>
  <li><a href="#fórmulas-benjumea" id="toc-fórmulas-benjumea" class="nav-link" data-scroll-target="#fórmulas-benjumea">Fórmulas Benjumea</a>
  <ul class="collapse">
  <li><a href="#lrt-antropómetro-3" id="toc-lrt-antropómetro-3" class="nav-link" data-scroll-target="#lrt-antropómetro-3">LRT Antropómetro</a></li>
  <li><a href="#lrt-cinta-métrica-3" id="toc-lrt-cinta-métrica-3" class="nav-link" data-scroll-target="#lrt-cinta-métrica-3">LRT cinta métrica</a></li>
  <li><a href="#resumen-fórmulas-benjumea" id="toc-resumen-fórmulas-benjumea" class="nav-link" data-scroll-target="#resumen-fórmulas-benjumea">Resumen fórmulas Benjumea</a></li>
  </ul></li>
  <li><a href="#fórmulas-arango-y-zamora" id="toc-fórmulas-arango-y-zamora" class="nav-link" data-scroll-target="#fórmulas-arango-y-zamora">Fórmulas Arango y Zamora</a>
  <ul class="collapse">
  <li><a href="#lrm-pierna-estirada-3" id="toc-lrm-pierna-estirada-3" class="nav-link" data-scroll-target="#lrm-pierna-estirada-3">LRM pierna estirada</a></li>
  <li><a href="#lrm-pierna-a-90-2" id="toc-lrm-pierna-a-90-2" class="nav-link" data-scroll-target="#lrm-pierna-a-90-2">LRM pierna a 90°</a></li>
  <li><a href="#resumen-fórmulas-arango-y-zamora" id="toc-resumen-fórmulas-arango-y-zamora" class="nav-link" data-scroll-target="#resumen-fórmulas-arango-y-zamora">Resumen fórmulas Arango y Zamora</a></li>
  </ul></li>
  <li><a href="#conclusión" id="toc-conclusión" class="nav-link" data-scroll-target="#conclusión">Conclusión</a></li>
  <li><a href="#comportamiento-de-las-variables-de-interés-por-subgrupos" id="toc-comportamiento-de-las-variables-de-interés-por-subgrupos" class="nav-link" data-scroll-target="#comportamiento-de-las-variables-de-interés-por-subgrupos">Comportamiento de las variables de interés por subgrupos</a>
  <ul class="collapse">
  <li><a href="#sexo-femenino" id="toc-sexo-femenino" class="nav-link" data-scroll-target="#sexo-femenino">Sexo femenino</a></li>
  <li><a href="#sexo-masculino" id="toc-sexo-masculino" class="nav-link" data-scroll-target="#sexo-masculino">Sexo masculino</a></li>
  </ul></li>
  <li><a href="#cuadro-modelos-predicción-de-la-talla-por-sexo" id="toc-cuadro-modelos-predicción-de-la-talla-por-sexo" class="nav-link" data-scroll-target="#cuadro-modelos-predicción-de-la-talla-por-sexo">Cuadro Modelos predicción de la talla por sexo</a>
  <ul class="collapse">
  <li><a href="#opción-1-modelo-normal-lrt_a" id="toc-opción-1-modelo-normal-lrt_a" class="nav-link" data-scroll-target="#opción-1-modelo-normal-lrt_a">Opción 1: Modelo normal LRT_A</a></li>
  <li><a href="#opción-2-modelo-normal-lrt_cm" id="toc-opción-2-modelo-normal-lrt_cm" class="nav-link" data-scroll-target="#opción-2-modelo-normal-lrt_cm">Opción 2: Modelo normal LRT_CM</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-page-left" id="quarto-document-content">



<section id="modelos" class="level1">
<h1>Modelos</h1>
<p>En esta sección se ajustarán tres tipos de modelos —Normal, LASSO y Gamma— para estimar la talla de adultos mayores en Colombia, utilizando diferentes mediciones: LRT_A, LRT_CM, LRM_R y LRM_90.</p>
<p>La elección de estos modelos se basa en la revisión de la literatura, que indica que las tallas suelen seguir una distribución normal. Además, se incluyen los modelos LASSO y Gamma debido a la naturaleza de la variable respuesta (talla), que es siempre positiva, lo que los hace adecuados para este tipo de datos.</p>
<section id="modelo-normal" class="level2">
<h2 class="anchored" data-anchor-id="modelo-normal">Modelo Normal</h2>
<section id="lrt-antropómetro" class="level3">
<h3 class="anchored" data-anchor-id="lrt-antropómetro">LRT Antropómetro</h3>
<p>Se hace una búsqueda del mejor modelo normal por cada número de posibles combinaciones de variables de las cuales se tenga evidencia que influyen en la talla de adultos mayores (Edad, Sexo, Etnia y LRT_A). Primero se hará la búsqueda usando todo el conjunto de datos.</p>
<p>A continuación, se muestra el BIC para cada mejor modelo del correspondiente tamaño:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] -869.8783 -907.9493 -924.4497 -919.9051 -915.3551 -910.8365</code></pre>
</div>
</div>
<p>Usando el criterio del BIC, el mejor modelo es el de 3 variables:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
<div class="cell-output-display">
<p><img src="modelos---copia_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="modelos---copia_files/figure-html/unnamed-chunk-7-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Los coeficientes del mejor modelo usando el criterio de BIC son:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)         LRT_A          Edad SexoMasculino 
   58.8428454     2.1763364    -0.1096942     3.2256625 </code></pre>
</div>
</div>
<p>Esto sugiere usar el modelo <span class="math inline">\(Talla = 59.11 + 2.19 LRT\_A - 0.12 Edad + 3.06 Sexo\)</span>,<br>
<span class="math display">\[Sexo = \begin{cases} 1 &amp; \text{si sexo = masculino} \\ 0 &amp; \text{si sexo = femenino} \end{cases}\]</span></p>
<p>Ahora se usará <strong><em>K - fold cross validation</em></strong> con el fin de calcular directamente los errores de predicción sobre los datos de testeo y evitar así el sobreajuste.</p>
<ul>
<li>Se crean <strong><em>K - folds</em></strong> (pliegues) de aproximadamente igual tamaño. En este caso fijamos <span class="math inline">\(k = 10\)</span>. Como tenemos <span class="math inline">\(543\)</span> datos, cada pliegue será de tamaño 54 o 55.</li>
<li>El <span class="math inline">\(k-ésimo\)</span> pliegue servirá para testear, y los demás pliegues se juntan para entrenar los modelos. Osea que se usará un <span class="math inline">\(90\%\)</span> de los datos para entrenamiento y <span class="math inline">\(10\%\)</span> para test.</li>
<li>Para <span class="math inline">\(k = 1,\cdots,10,\)</span> se calcula el MSE.</li>
<li>Luego, se promedia el MSE a través de los <span class="math inline">\(10\)</span> pliegues y se obtiene el MSE promedio.</li>
</ul>
<p>El MSE para el modelo de 3 variables (<span class="math inline">\(LRT\_A, Edad, Sexo\)</span>) es:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10.14466</code></pre>
</div>
</div>
</section>
<section id="lrt-cinta-métrica" class="level3">
<h3 class="anchored" data-anchor-id="lrt-cinta-métrica">LRT cinta métrica</h3>
<p>Se hace una búsqueda del mejor modelo normal por cada número de posibles combinaciones de variables de las cuales se tenga evidencia que influyen en la talla de adultos mayores (Edad, Sexo, Etnia y LRT_CM). Primero se hará la búsqueda usando todo el conjunto de datos.</p>
<p>A continuación, se muestra el BIC para cada mejor modelo del correspondiente tamaño:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] -785.0072 -854.2349 -869.3562 -864.2374 -859.6006 -853.6608</code></pre>
</div>
</div>
<p>Usando el criterio BIC, el mejor modelo es el de 3 variables:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
<div class="cell-output-display">
<p><img src="modelos---copia_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="modelos---copia_files/figure-html/unnamed-chunk-13-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Los coeficientes del mejor modelo usando el criterio de BIC son:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)        LRT_CM          Edad SexoMasculino 
   56.7788743     2.1486596    -0.1131516     4.3001219 </code></pre>
</div>
</div>
<p>Esto sugiere usar el modelo <span class="math inline">\(Talla = 57.30 + 2.16 LRT\_CM - 0.13 Edad + 4.13 Sexo\)</span>,<br>
<span class="math display">\[Sexo = \begin{cases} 1 &amp; \text{si sexo = Masculino} \\ 0 &amp; \text{si sexo = Femenino} \end{cases}\]</span></p>
<p>Ahora usamos nuevamente <strong><em>K - fold cross validation</em></strong> con el fin de calcular directamente los errores de predicción sobre los datos de testeo y evitar así el sobreajuste de la misma manera que se realizó para el modelo normal de <span class="math inline">\(LRT_A\)</span>.</p>
<p>El MSE para el modelo de 3 variables (<span class="math inline">\(LRT\_CM, Edad, Sexo\)</span>) es:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11.52624</code></pre>
</div>
</div>
</section>
<section id="lrm-pierna-estirada" class="level3">
<h3 class="anchored" data-anchor-id="lrm-pierna-estirada">LRM pierna estirada</h3>
<p>Se hace una búsqueda del mejor modelo normal por cada número de posibles combinaciones de variables de las cuales se tenga evidencia que influyen en la talla de adultos mayores (Edad, Sexo, Etnia y LRM_R). Primero se hará la búsqueda usando todo el conjunto de datos.</p>
<p>A continuación, se muestra el BIC para cada mejor modelo del correspondiente tamaño:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] -770.6371 -814.0382 -823.5290 -818.9141 -814.1528 -810.4009</code></pre>
</div>
</div>
<p>Usando el criterio BIC, el mejor modelo es el de 3 variables:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
<div class="cell-output-display">
<p><img src="modelos---copia_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="modelos---copia_files/figure-html/unnamed-chunk-19-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Los coeficientes del mejor modelo usando el criterio de BIC son:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)         LRM_R          Edad SexoMasculino 
   67.2117181     2.2173933    -0.1018772     3.7494134 </code></pre>
</div>
</div>
<p>Esto sugiere usar el modelo <span class="math inline">\(Talla = 68.04 + 2.21 LRM\_R - 0.11 Edad + 3.81 Sexo\)</span>,<br>
<span class="math display">\[Sexo = \begin{cases} 1 &amp; \text{si sexo = Masculino} \\ 0 &amp; \text{si sexo = Femenino} \end{cases}\]</span></p>
<p>Nuevamente, se hará la búsqueda del mejor modelo usando <strong><em>K - fold cross validation</em></strong> con el fin de calcular directamente los errores de predicción sobre los datos de testeo y evitar así el sobreajuste.</p>
<p>El MSE para el modelo de 3 variables (<span class="math inline">\(LRM\_R, Edad, Sexo\)</span>) es:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12.83537</code></pre>
</div>
</div>
</section>
<section id="lrm-pierna-a-90" class="level3">
<h3 class="anchored" data-anchor-id="lrm-pierna-a-90">LRM pierna a 90°</h3>
<p>Se hace una búsqueda del mejor modelo normal por cada número de posibles combinaciones de variables de las cuales se tenga evidencia que influyen en la talla de adultos mayores (Edad, Sexo, Etnia y LRM_90). Primero se hará la búsqueda usando todo el conjunto de datos.</p>
<p>A continuación, se muestra el BIC para cada mejor modelo del correspondiente tamaño:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] -724.1015 -810.4493 -819.5010 -813.7540 -808.3704 -803.4330</code></pre>
</div>
</div>
<p>Usando el criterio BIC, el mejor modelo es el de 3 variables:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
<div class="cell-output-display">
<p><img src="modelos---copia_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="modelos---copia_files/figure-html/unnamed-chunk-25-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Los coeficientes del mejor modelo usando el criterio de BIC son:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)        LRM_90          Edad SexoMasculino 
   65.9041633     2.1944725    -0.1008714     4.9118635 </code></pre>
</div>
</div>
<p>Esto sugiere usar el modelo <span class="math inline">\(Talla = 66.20 + 2.22 LRM\_90 - 0.12 Edad + 4.83 Sexo\)</span>,<br>
<span class="math display">\[Sexo = \begin{cases} 1 &amp; \text{si sexo = Masculino} \\ 0 &amp; \text{si sexo = Femenino} \end{cases}\]</span></p>
<p>Ahora se hará la búsqueda del mejor modelo usando <strong><em>K - fold cross validation</em></strong> con el fin de calcular directamente los errores de predicción sobre los datos de testeo y evitar así el sobreajuste.</p>
<p>El MSE para el modelo de 3 variables (<span class="math inline">\(LRM\_90, Edad, Sexo\)</span>) es:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12.97915</code></pre>
</div>
</div>
</section>
<section id="resúmen-modelos-normal" class="level3">
<h3 class="anchored" data-anchor-id="resúmen-modelos-normal">Resúmen modelos Normal</h3>
<p>En general, los modelos ajustados incluyeron como variables la edad, el sexo y el intercepto, variando únicamente entre las mediciones utilizadas: LRT_A, LRT_CM, LRM_90 y LRM_R. Cada modelo produjo diferentes estimaciones para los parámetros, lo que resulta en ecuaciones distintas para estimar la talla de los adultos mayores.</p>
<p>El criterio principal para seleccionar el mejor modelo, ya sea normal o de otro tipo, será <strong>el menor error cuadrático medio (MSE)</strong>. Esto se debe a que un MSE más bajo indica que el modelo realiza estimaciones de la talla más cercanas a los valores reales, reflejando una mayor precisión.</p>
<p>La tabla de los errores cuadráticos medios para la regresión lineal simple es la siguiente:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  Modelo Medida      MSE
1 Normal  LRT_A 10.14466
2 Normal LRT_CM 11.52624
3 Normal  LRM_R 12.83537
4 Normal LRM_90 12.97915</code></pre>
</div>
</div>
<p>El modelo con menor error cuadrático medio es el que tiene en cuenta la medida LRT con antropómetro:</p>
<p><span class="math display">\[Talla = 59.11 + 2.19 LRT\_A - 0.12 Edad + 3.06 Sexo\]</span></p>
<p>A continuación, se procederá a validar los supuestos del mejor modelo identificado. Esta validación es crucial, ya que si los supuestos no se cumplen, el modelo no puede considerarse válido y sus resultados podrían no ser confiables.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Talla ~ LRT_A + Edad + Sexo, data = datos)

Residuals:
     Min       1Q   Median       3Q      Max 
-10.6057  -1.9307   0.0574   2.3335   8.5648 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   58.84285    3.15618  18.644  &lt; 2e-16 ***
LRT_A          2.17634    0.05994  36.310  &lt; 2e-16 ***
Edad          -0.10969    0.02289  -4.792 2.28e-06 ***
SexoMasculino  3.22566    0.42876   7.523 3.14e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.17 on 431 degrees of freedom
Multiple R-squared:  0.8871,    Adjusted R-squared:  0.8863 
F-statistic:  1129 on 3 and 431 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>El modelo tiene un <span class="math inline">\(R^2\)</span> ajustado de <span class="math inline">\(0.8856\)</span>, es decir que aproximadamente un <span class="math inline">\(88.56\%\)</span> de la variabilidad de la talla es explicada por LRT_A, la edad y el sexo.</p>
<p><strong><em>Linealidad:</em></strong> Con el fin de verificar que la relación entre la talla y las variables LRT_A (discriminando por sexo) y la edad es lineal, se visualiza el gráfico de los residuos vs los valores predichos del modelo <span class="math inline">\(\left(\hat{e},\hat{y} \right)\)</span>:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="modelos---copia_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>El gráfico no muestra ningún patrón marcado, la ubicación de los puntos parece ser aleatoria alrededor de cero, indicando también homoscedasticidad en los residuales y posible independencia de los mismos. El gráfico muestra algunos valores atípicos que valdría la pena explorar.</p>
<p><strong><em>Independencia de los errores:</em></strong> Aunque nuestros datos no son temporales, el test de Durbin-Watson nos puede ayudar a evaluar la autocorrelación de los errores del modelo:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Durbin-Watson test

data:  reg
DW = 2.1354, p-value = 0.9191
alternative hypothesis: true autocorrelation is greater than 0</code></pre>
</div>
</div>
<p>La estadística del test de Durbin-Watson es muy cercano a <span class="math inline">\(2\)</span>, se concluye que los errores son independientes.</p>
<p><strong><em>Normalidad de los errores:</em></strong> Se realiza el gráfico QQ-plot para comparar la distribución de los residuales del modelo con la distribución teórica de una normal. También se hace el test de normalidad de Lilliefors y Anderson-Darling:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="modelos---copia_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Lilliefors (Kolmogorov-Smirnov) normality test

data:  reg$residuals
D = 0.028887, p-value = 0.5079</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Anderson-Darling normality test

data:  reg$residuals
A = 0.51324, p-value = 0.1926</code></pre>
</div>
</div>
<p>El QQ-plot muestra que los residuales se ajustan aceptablemente a una distribución normal. Las pruebas de normalidad de Lilliefors y Anderson-Darling también apoyan este resultado.</p>
<p><strong><em>Homoscedasticidad:</em></strong> Aunque no se vio un patron que indicara heteroscedasticidad en el gráfico de los residuales vs los valores predichos, a continuación se muestra el gráfico de los residuales estandarizados vs los valores predichos con el fin de mejorar la interpretabilidad de la homoscedasticidad y tener una visión más clara de las observaciones atípicas e influyentes:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="modelos---copia_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>No se observan patrones que indiquen hereroscedasticidad en los residuos (forma de cono o embudo). Se siguien observando algunas observaciones atípicas y/o influyentes.</p>
<p>Adicional, se realiza la prueba de Breusch-Pagan para verificar la homoscedasticidad de los residuales:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    studentized Breusch-Pagan test

data:  reg
BP = 1.5378, df = 3, p-value = 0.6736</code></pre>
</div>
</div>
<p>No se rechaza la hipótesis nula de que los errores del modelo son homoscedasticos.</p>
<p><strong><em>Multicolinealidad:</em></strong> Se verifica que las variables incluídas en el modelo no están altamente correlacionadas entre sí, y así evitar obtener resultados inestables que dificulten la interpretabilidad de los coeficientes del modelo. Se calculan los Factores de Inflación de la Varianza (VIFs):</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   LRT_A     Edad     Sexo 
1.955928 1.034172 1.988986 </code></pre>
</div>
</div>
<p>Dado que los VIFs son mucho menores a 5, esto indica que cada variable tiene una correlación moderada (leve) con las demás. Por lo que se puede concluir que los resultados del modelo posiblemente no estarán muy afectados por la multicolinealidad.</p>
<p><strong><em>El modelo está bien especificado:</em></strong> Se hace el test de RESET para examinar si el modelo ajustado está bien especificado o si se han omitido términos no lineales o interacciones importantes:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    RESET test

data:  reg
RESET = 1.0309, df1 = 4, df2 = 427, p-value = 0.3909</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    RESET test

data:  reg
RESET = 0.73692, df1 = 2, df2 = 429, p-value = 0.4792</code></pre>
</div>
</div>
<p>No se rechaza la hipótesis nula de que el modelo está bien especificado.</p>
<p><strong><em>Observaciones atípicas y de alto apalancamiento:</em></strong></p>
<div class="cell quarto-layout-panel">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="modelos---copia_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="modelos---copia_files/figure-html/unnamed-chunk-38-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
<p>Usando los residuales estudentizados, se observan <span class="math inline">\(5\)</span> datos atípicos.</p>
<div class="cell quarto-layout-panel">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="modelos---copia_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="modelos---copia_files/figure-html/unnamed-chunk-39-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<pre><code>       StudRes        Hat       CookD
25  -0.7292660 0.02933562 0.004022631
491 -2.6083060 0.01716950 0.029317535
520 -3.4102219 0.01403516 0.040390587
529 -2.8640783 0.01333301 0.027256453
538 -0.8522359 0.03089114 0.005791578</code></pre>
</div>
</div>
</div>
<p>En total 29 observaciones superan el umbral especificado para la distancia de Cook, pero esto no significa que todas sean influyentes (alto leverage). Particularmente hay 3 observaciones que son marcadas como influyentes significativamente según la distancia de Cook. Esto indica que la inclusión de estas observaciones en el modelo pueden tener una influencia significativa en los coeficientes del modelo y en la predicción de la talla. Se debe explorar con cautela estas observaciones y decidir qué hacer con ellas.</p>
<p>Para esto, se puede comprobar el cambio en los coeficientes del modelo al excluir estas observaciones influyentes.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Talla ~ LRT_A + Edad + Sexo, data = datos, subset = {
    setdiff(row(datos)[, 1], c(533, 43, 549))
})

Residuals:
     Min       1Q   Median       3Q      Max 
-10.6058  -1.9277   0.0483   2.3297   8.5671 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   58.96460    3.16648  18.622  &lt; 2e-16 ***
LRT_A          2.17491    0.06004  36.224  &lt; 2e-16 ***
Edad          -0.11051    0.02296  -4.813 2.06e-06 ***
SexoMasculino  3.22663    0.42911   7.519 3.24e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.173 on 430 degrees of freedom
Multiple R-squared:  0.8867,    Adjusted R-squared:  0.8859 
F-statistic:  1122 on 3 and 430 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Las estimaciones de los coeficientes del modelo sin las obervaciones influyentes han cambiado un poco respecto al modelo original. El <span class="math inline">\(R^2\)</span> ajustado ha incrementado un poco también.</p>
</section>
</section>
<section id="modelo-lasso" class="level2">
<h2 class="anchored" data-anchor-id="modelo-lasso">Modelo Lasso</h2>
<section id="lrt-antropómetro-1" class="level3">
<h3 class="anchored" data-anchor-id="lrt-antropómetro-1">LRT Antropómetro</h3>
<p>Para ajustar el modelo LASSO, se consideran todas las variables que podrían influir en la estimación de la talla: Edad, Sexo, Etnia y LRT_A. El modelo se encargará automáticamente de seleccionar las variables más significativas.</p>
<p>Se utiliza el método de <strong><em>k-fold cross validation</em></strong> con <span class="math inline">\(k = 10\)</span> usando los mismos folds utilizados en el modelo normal para que las métricas sean comparables. El objetivo principal de la validación cruzada en el modelo LASSO es obtener el valor de <span class="math inline">\(\lambda\)</span> que minimice el error cuadrático medio cruzado a través de los 10 folds. Es decir, se busca el valor de <span class="math inline">\(\lambda\)</span> que minimice el MSE a través de los 10 folds (lo mismo que en el modelo normal).</p>
<p>El modelo LASSO ajusta los coeficientes de las variables, llevando a cero aquellos que no son significativos. Además, determina de forma óptima el parámetro lambda que controla la penalización y selección de variables.</p>
<p>Se ajusta el modelo en cada fold usando <code>cv.glmnet</code>:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="modelos---copia_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>El valor de <span class="math inline">\(\lambda\)</span> óptimo y el MSE del modelo ajustado con ese valor de <span class="math inline">\(\lambda\)</span> son respectivamente:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Valor de lambda óptimo: 0.099"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "MSE: 10.186"</code></pre>
</div>
</div>
<p>Los coeficientes resultantes del modelo ajustado son:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>7 x 1 sparse Matrix of class "dgCMatrix"
                             s1
(Intercept)         58.49212479
LRT_A                2.15790258
Edad                -0.09165771
SexoMasculino        3.07058891
EtniaBlanco-Mestizo  .         
EtniaIndigena        0.87257838
EtniaRrom            .         </code></pre>
</div>
</div>
<p>Finalmente, la ecuación propuesta por este modelo para estimar la talla en adultos mayores es:</p>
<p><span class="math display">\[Talla = 58.514 + 2.174 \cdot LRT\_A - 0.102 \cdot Edad + 2.870 \cdot SexoMasculino + 0.037 \cdot EtniaIndigena\]</span> <span class="math display">\[Sexo = \begin{cases} 1 &amp; \text{si sexo = Masculino} \\ 0 &amp; \text{si sexo = Femenino} \end{cases}\]</span> <span class="math display">\[BM = \begin{cases} 1 &amp; \text{si Etnia = Blanco-Mestizo} \\ 0 &amp; \text{en otro caso} \end{cases}\]</span> <span class="math display">\[Ind = \begin{cases} 1 &amp; \text{si Etnia = Indígena} \\ 0 &amp; \text{en otro caso} \end{cases}\]</span></p>
</section>
<section id="lrt-cinta-métrica-1" class="level3">
<h3 class="anchored" data-anchor-id="lrt-cinta-métrica-1">LRT cinta métrica</h3>
<p>Para ajustar el modelo LASSO, se consideran todas las variables que podrían influir en la estimación de la talla: Edad, Sexo, Etnia y LRT_CM. El modelo se encargará automáticamente de seleccionar las variables más significativas.</p>
<p>Se utiliza el método de <strong><em>k-fold cross validation</em></strong> con <span class="math inline">\(k = 10\)</span> usando los mismos folds utilizados en el modelo normal para que las métricas sean comparables. El objetivo principal de la validación cruzada en el modelo LASSO es obtener el valor de <span class="math inline">\(\lambda\)</span> que minimice el error cuadrático medio cruzado a través de los 10 folds. Es decir, se busca el valor de <span class="math inline">\(\lambda\)</span> que minimice el MSE a través de los 10 folds (lo mismo que en el modelo normal).</p>
<p>El modelo LASSO ajusta los coeficientes de las variables, llevando a cero aquellos que no son significativos. Además, determina de forma óptima el parámetro lambda que controla la penalización y selección de variables.</p>
<p>Se ajusta el modelo en cada fold usando <code>cv.glmnet</code>:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="modelos---copia_files/figure-html/unnamed-chunk-47-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>El valor de <span class="math inline">\(\lambda\)</span> óptimo y el MSE del modelo ajustado con ese valor de <span class="math inline">\(\lambda\)</span> son respectivamente:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Valor de lambda óptimo: 0.008"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "MSE: 11.542"</code></pre>
</div>
</div>
<p>Los coeficientes resultantes del modelo ajustado son:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>7 x 1 sparse Matrix of class "dgCMatrix"
                            s1
(Intercept)         55.0472932
LRT_CM               2.1472901
Edad                -0.1131422
SexoMasculino        4.3041272
EtniaBlanco-Mestizo  1.7987785
EtniaIndigena        3.1804166
EtniaRrom            0.9271863</code></pre>
</div>
</div>
<p>Finalmente, la ecuación propuesta por este modelo para estimar la talla en adultos mayores es:</p>
<p><span class="math display">\[Talla = 56.831 + 2.146 \cdot LRT\_CM - 0.110 \cdot Edad + 3.951 \cdot Sexo\]</span><br>
<span class="math display">\[Sexo = \begin{cases} 1 &amp; \text{si sexo = Masculino} \\ 0 &amp; \text{si sexo = Femenino} \end{cases}\]</span><br>
</p>
</section>
<section id="lrm-pierna-estirada-1" class="level3">
<h3 class="anchored" data-anchor-id="lrm-pierna-estirada-1">LRM pierna estirada</h3>
<p>Para ajustar el modelo LASSO, se consideran todas las variables que podrían influir en la estimación de la talla: Edad, Sexo, Etnia y LRM_R. El modelo se encargará automáticamente de seleccionar las variables más significativas.</p>
<p>Se utiliza el método de <strong><em>k-fold cross validation</em></strong> con <span class="math inline">\(k = 10\)</span> usando los mismos folds utilizados en el modelo normal para que las métricas sean comparables. El objetivo principal de la validación cruzada en el modelo LASSO es obtener el valor de <span class="math inline">\(\lambda\)</span> que minimice el error cuadrático medio cruzado a través de los 10 folds. Es decir, se busca el valor de <span class="math inline">\(\lambda\)</span> que minimice el MSE a través de los 10 folds (lo mismo que en el modelo normal).</p>
<p>El modelo LASSO ajusta los coeficientes de las variables, llevando a cero aquellos que no son significativos. Además, determina de forma óptima el parámetro lambda que controla la penalización y selección de variables.</p>
<p>Se ajusta el modelo en cada fold usando <code>cv.glmnet</code>:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="modelos---copia_files/figure-html/unnamed-chunk-51-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>El valor de <span class="math inline">\(\lambda\)</span> óptimo y el MSE del modelo ajustado con ese valor de <span class="math inline">\(\lambda\)</span> son respectivamente:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Valor de lambda óptimo: 0.005"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "MSE: 12.828"</code></pre>
</div>
</div>
<p>Los coeficientes resultantes del modelo ajustado son:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>7 x 1 sparse Matrix of class "dgCMatrix"
                           s1
(Intercept)         64.530104
LRM_R                2.216361
Edad                -0.103810
SexoMasculino        3.753767
EtniaBlanco-Mestizo  2.860621
EtniaIndigena        4.717920
EtniaRrom            5.746844</code></pre>
</div>
</div>
<p>Finalmente, la ecuación propuesta por este modelo para estimar la talla en adultos mayores es:</p>
<p><span class="math display">\[Talla = 65.525 + 2.217 \cdot LRM\_R - 0.116 \cdot Edad + 3.797 \cdot Sexo + 2.568 \cdot BM + 3.508 \cdot Ind + 5.314 \cdot Rrom\]</span><br>
<span class="math display">\[Sexo = \begin{cases} 1 &amp; \text{si sexo = Masculino} \\ 0 &amp; \text{si sexo = Femenino} \end{cases}\]</span><br>
<span class="math display">\[BM = \begin{cases} 1 &amp; \text{si Etnia = Blanco-Mestizo} \\ 0 &amp; \text{en otro caso} \end{cases}\]</span><br>
<span class="math display">\[Ind = \begin{cases} 1 &amp; \text{si Etnia = Indigena} \\ 0 &amp; \text{en otro caso} \end{cases}\]</span><br>
<span class="math display">\[Rrom = \begin{cases} 1 &amp; \text{si Etnia = Rrom} \\ 0 &amp; \text{en otro caso} \end{cases}\]</span></p>
</section>
<section id="lrm-pierna-a-90-1" class="level3">
<h3 class="anchored" data-anchor-id="lrm-pierna-a-90-1">LRM pierna a 90°</h3>
<p>Para ajustar el modelo LASSO, se consideran todas las variables que podrían influir en la estimación de la talla: Edad, Sexo, Etnia y LRM_90. El modelo se encargará automáticamente de seleccionar las variables más significativas.</p>
<p>Se utiliza el método de <strong><em>k-fold cross validation</em></strong> con <span class="math inline">\(k = 10\)</span> usando los mismos folds utilizados en el modelo normal para que las métricas sean comparables. El objetivo principal de la validación cruzada en el modelo LASSO es obtener el valor de <span class="math inline">\(\lambda\)</span> que minimice el error cuadrático medio cruzado a través de los 10 folds. Es decir, se busca el valor de <span class="math inline">\(\lambda\)</span> que minimice el MSE a través de los 10 folds (lo mismo que en el modelo normal).</p>
<p>El modelo LASSO ajusta los coeficientes de las variables, llevando a cero aquellos que no son significativos. Además, determina de forma óptima el parámetro lambda que controla la penalización y selección de variables.</p>
<p>Se ajusta el modelo en cada fold usando <code>cv.glmnet</code>:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="modelos---copia_files/figure-html/unnamed-chunk-55-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>El valor de <span class="math inline">\(\lambda\)</span> óptimo y el MSE del modelo ajustado con ese valor de <span class="math inline">\(\lambda\)</span> son respectivamente:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Valor de lambda óptimo: 0.077"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "MSE: 13.005"</code></pre>
</div>
</div>
<p>Los coeficientes resultantes del modelo ajustado son:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>7 x 1 sparse Matrix of class "dgCMatrix"
                             s1
(Intercept)         65.62591887
LRM_90               2.17921716
Edad                -0.08695065
SexoMasculino        4.78312097
EtniaBlanco-Mestizo  .         
EtniaIndigena        0.19566037
EtniaRrom            0.51369340</code></pre>
</div>
</div>
<p>Finalmente, la ecuación propuesta por este modelo para estimar la talla en adultos mayores es:</p>
<p><span class="math display">\[Talla = 65.493 + 2.205 \cdot LRM\_90 - 0.105 \cdot Edad + 4.688 \cdot Sexo + 0.294 \cdot BM + 0.612 \cdot Rrom\]</span><br>
<span class="math display">\[Sexo = \begin{cases} 1 &amp; \text{si sexo = Masculino} \\ 0 &amp; \text{si sexo = Femenino} \end{cases}\]</span><br>
<span class="math display">\[BM = \begin{cases} 1 &amp; \text{si Etnia = Blanco-Mestizo} \\ 0 &amp; \text{en otro caso} \end{cases}\]</span><br>
<span class="math display">\[Rrom = \begin{cases} 1 &amp; \text{si Etnia = Rrom} \\ 0 &amp; \text{en otro caso} \end{cases}\]</span></p>
</section>
<section id="resumen-modelos-lasso" class="level3">
<h3 class="anchored" data-anchor-id="resumen-modelos-lasso">Resumen modelos LASSO</h3>
<p>En general, los modelos ajustados incluyeron más variables que las tres del modelo normal (edad, sexo y mediciones). Cada modelo produjo diferentes estimaciones para los parámetros, lo que resulta en ecuaciones distintas para estimar la talla de los adultos mayores.</p>
<p>Nuevamente, es preferible el modelo LASSO que tenga menor error cuadrático medio. Y en general, es preferible el modelo (normal o LASSO) que tenga menor MSE.</p>
<p>La tabla de los errores cuadráticos medios de los modelos ajustados hasta el momento es:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  Modelo Medida      MSE
5  LASSO  LRT_A 10.18571
6  LASSO LRT_CM 11.54195
7  LASSO  LRM_R 12.82789
8  LASSO LRM_90 13.00511</code></pre>
</div>
</div>
<p>El modelo normal con LRT_A sigue siendo el mejor, ya que hasta el momento es el que presenta el menor MSE. Por lo tanto, no se procederá a verificar los supuestos para ninguno de los modelos LASSO, dado que el modelo normal continúa siendo superior.</p>
</section>
</section>
<section id="modelo-gamma" class="level2">
<h2 class="anchored" data-anchor-id="modelo-gamma">Modelo Gamma</h2>
<section id="lrt-antropómetro-2" class="level3">
<h3 class="anchored" data-anchor-id="lrt-antropómetro-2">LRT Antropómetro</h3>
<p>Inicialmente, se ajusta el modelo Gamma que incluye a todas las variables regresoras que se cree influyen en la estimación de la talla.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Talla ~ LRT_A + Edad + Etnia + Sexo, family = Gamma(), 
    data = datos)

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)          1.046e-02  1.487e-04  70.307  &lt; 2e-16 ***
LRT_A               -8.778e-05  2.517e-06 -34.880  &lt; 2e-16 ***
Edad                 4.542e-06  9.714e-07   4.676 3.93e-06 ***
EtniaBlanco-Mestizo -1.134e-04  6.586e-05  -1.721   0.0859 .  
EtniaIndigena       -1.862e-04  8.716e-05  -2.137   0.0332 *  
EtniaRrom           -1.647e-04  1.396e-04  -1.180   0.2387    
SexoMasculino       -1.378e-04  1.817e-05  -7.587 2.06e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for Gamma family taken to be 0.0004379319)

    Null deviance: 1.57735  on 434  degrees of freedom
Residual deviance: 0.18837  on 428  degrees of freedom
AIC: 2274.7

Number of Fisher Scoring iterations: 3</code></pre>
</div>
</div>
<p>A continuación se realiza una selección de variables con el método “forward” de tal forma que se minimice el AIC. El modelo seleccionado resulta ser el que incluye Edad, Sexo y LRT_A.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=3187.34
Talla ~ 1

        Df Deviance    AIC
+ LRT_A  1  0.22113 2814.8
+ Sexo   1  0.73444 2956.6
&lt;none&gt;      1.57735 3187.3
+ Edad   1  1.57197 3187.9
+ Etnia  3  1.56020 3188.6

Step:  AIC=2334.45
Talla ~ LRT_A

        Df Deviance    AIC
+ Sexo   1  0.19960 2294.1
+ Edad   1  0.21541 2325.2
&lt;none&gt;      0.22113 2334.4
+ Etnia  3  0.21965 2337.5

Step:  AIC=2291.88
Talla ~ LRT_A + Sexo

        Df Deviance    AIC
+ Edad   1  0.19048 2274.0
&lt;none&gt;      0.19960 2291.9
+ Etnia  3  0.19796 2294.3

Step:  AIC=2273.53
Talla ~ LRT_A + Sexo + Edad

        Df Deviance    AIC
&lt;none&gt;      0.19048 2273.5
+ Etnia  3  0.18837 2274.7</code></pre>
</div>
</div>
<p>Los coeficientes del modelo son</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Talla ~ LRT_A + Edad + Sexo, family = Gamma(), 
    data = datos)

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    1.035e-02  1.332e-04  77.730  &lt; 2e-16 ***
LRT_A         -8.776e-05  2.512e-06 -34.932  &lt; 2e-16 ***
Edad           4.417e-06  9.704e-07   4.552 6.93e-06 ***
SexoMasculino -1.370e-04  1.820e-05  -7.531 2.98e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for Gamma family taken to be 0.0004397181)

    Null deviance: 1.57735  on 434  degrees of freedom
Residual deviance: 0.19047  on 431  degrees of freedom
AIC: 2273.5

Number of Fisher Scoring iterations: 3</code></pre>
</div>
</div>
<p>Entonces, la ecuación propuesta por este modelo para estimar el logaritmo de la talla en adultos mayores es:</p>
<p><span class="math display">\[\ln(Talla) = 0.01033 - 0.00008813 LRT\_A + 0.000004989 Edad - 0.0001318 Sexo\]</span><br>
<span class="math display">\[Sexo = \begin{cases} 1 &amp; \text{si sexo = Masculino} \\ 0 &amp; \text{si sexo = Femenino} \end{cases}\]</span><br>
</p>
<p>Se utiliza el método de<strong><em>k-fold cross validation</em></strong> con <span class="math inline">\(k = 10\)</span> y y se calcula el promedio del MSE obtenido en cada iteración. El MSE para este modelo es:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10.6452</code></pre>
</div>
</div>
</section>
<section id="lrt-cinta-métrica-2" class="level3">
<h3 class="anchored" data-anchor-id="lrt-cinta-métrica-2">LRT cinta métrica</h3>
<p>Inicialmente, se ajusta el modelo Gamma que incluye a todas las variables regresoras que se cree influyen en la estimación de la talla.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Talla ~ LRT_CM + Edad + Etnia + Sexo, family = Gamma(), 
    data = datos)

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)          1.054e-02  1.623e-04  64.925  &lt; 2e-16 ***
LRT_CM              -8.687e-05  2.709e-06 -32.067  &lt; 2e-16 ***
Edad                 4.592e-06  1.031e-06   4.456 1.07e-05 ***
EtniaBlanco-Mestizo -9.189e-05  6.994e-05  -1.314    0.190    
EtniaIndigena       -1.509e-04  9.259e-05  -1.630    0.104    
EtniaRrom           -4.257e-05  1.484e-04  -0.287    0.774    
SexoMasculino       -1.805e-04  1.861e-05  -9.697  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for Gamma family taken to be 0.0004942473)

    Null deviance: 1.5774  on 434  degrees of freedom
Residual deviance: 0.2122  on 428  degrees of freedom
AIC: 2326.5

Number of Fisher Scoring iterations: 3</code></pre>
</div>
</div>
<p>A continuación se realiza una selección de variables con el método “forward” de tal forma que se minimice el AIC. El modelo seleccionado resulta ser el que incluye Edad, Sexo y LRT_A.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=3187.34
Talla ~ 1

         Df Deviance    AIC
+ LRT_CM  1  0.26454 2826.8
+ Sexo    1  0.73444 2956.6
&lt;none&gt;       1.57735 3187.3
+ Edad    1  1.57197 3187.9
+ Etnia   3  1.56020 3188.6

Step:  AIC=2412.42
Talla ~ LRT_CM

        Df Deviance    AIC
+ Sexo   1  0.22310 2346.6
+ Edad   1  0.25969 2406.5
&lt;none&gt;      0.26454 2412.4
+ Etnia  3  0.26369 2417.0

Step:  AIC=2340.3
Talla ~ LRT_CM + Sexo

        Df Deviance    AIC
+ Edad   1  0.21359 2323.8
&lt;none&gt;      0.22310 2340.3
+ Etnia  3  0.22202 2344.2

Step:  AIC=2323.36
Talla ~ LRT_CM + Sexo + Edad

        Df Deviance    AIC
&lt;none&gt;      0.21359 2323.4
+ Etnia  3  0.21219 2326.5</code></pre>
</div>
</div>
<p>Los coeficientes del modelo son</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Talla ~ LRT_CM + Edad + Sexo, family = Gamma(), 
    data = datos)

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    1.045e-02  1.461e-04  71.520  &lt; 2e-16 ***
LRT_CM        -8.680e-05  2.694e-06 -32.214  &lt; 2e-16 ***
Edad           4.502e-06  1.027e-06   4.383 1.47e-05 ***
SexoMasculino -1.797e-04  1.860e-05  -9.661  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for Gamma family taken to be 0.0004940556)

    Null deviance: 1.57735  on 434  degrees of freedom
Residual deviance: 0.21359  on 431  degrees of freedom
AIC: 2323.4

Number of Fisher Scoring iterations: 3</code></pre>
</div>
</div>
<p>Entonces, la ecuación propuesta por este modelo para estimar el logaritmo de la talla en adultos mayores es:</p>
<p><span class="math display">\[\ln(Talla) = 1.041e-02 - 8.703e-05 LRT\_CM + 5.205e-06 Edad - 1.745e-04 Sexo\]</span><br>
<span class="math display">\[Sexo = \begin{cases} 1 &amp; \text{si sexo = Masculino} \\ 0 &amp; \text{si sexo = Femenino} \end{cases}\]</span><br>
</p>
<p>Se utiliza el método de<strong><em>k-fold cross validation</em></strong> con <span class="math inline">\(k = 10\)</span> y y se calcula el promedio del MSE obtenido en cada iteración. El MSE para este modelo es:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11.86227</code></pre>
</div>
</div>
</section>
<section id="lrm-pierna-estirada-2" class="level3">
<h3 class="anchored" data-anchor-id="lrm-pierna-estirada-2">LRM pierna estirada</h3>
<p>Inicialmente, se ajusta el modelo Gamma que incluye a todas las variables regresoras que se cree influyen en la estimación de la talla.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Talla ~ LRM_R + Edad + Etnia + Sexo, family = Gamma(), 
    data = datos)

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)          1.014e-02  1.618e-04  62.706  &lt; 2e-16 ***
LRM_R               -8.963e-05  2.985e-06 -30.027  &lt; 2e-16 ***
Edad                 4.255e-06  1.080e-06   3.941 9.47e-05 ***
EtniaBlanco-Mestizo -1.327e-04  7.323e-05  -1.811   0.0708 .  
EtniaIndigena       -2.077e-04  9.686e-05  -2.144   0.0326 *  
EtniaRrom           -2.324e-04  1.551e-04  -1.498   0.1349    
SexoMasculino       -1.583e-04  2.015e-05  -7.860 3.16e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for Gamma family taken to be 0.0005409435)

    Null deviance: 1.57735  on 434  degrees of freedom
Residual deviance: 0.23282  on 428  degrees of freedom
AIC: 2366.9

Number of Fisher Scoring iterations: 3</code></pre>
</div>
</div>
<p>A continuación se realiza una selección de variables con el método “forward” de tal forma que se minimice el AIC. El modelo seleccionado resulta ser el que incluye Edad, Sexo y LRT_A.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=3187.34
Talla ~ 1

        Df Deviance    AIC
+ LRM_R  1  0.27302 2829.1
+ Sexo   1  0.73444 2956.6
&lt;none&gt;      1.57735 3187.3
+ Edad   1  1.57197 3187.9
+ Etnia  3  1.56020 3188.6

Step:  AIC=2426.15
Talla ~ LRM_R

        Df Deviance    AIC
+ Sexo   1  0.24354 2381.3
+ Edad   1  0.26889 2421.6
&lt;none&gt;      0.27302 2426.2
+ Etnia  3  0.27075 2428.6

Step:  AIC=2378.44
Talla ~ LRM_R + Sexo

        Df Deviance    AIC
+ Edad   1  0.23567 2366.4
&lt;none&gt;      0.24354 2378.4
+ Etnia  3  0.24124 2380.3

Step:  AIC=2366.15
Talla ~ LRM_R + Sexo + Edad

        Df Deviance    AIC
&lt;none&gt;      0.23567 2366.2
+ Etnia  3  0.23282 2366.9</code></pre>
</div>
</div>
<p>Los coeficientes del modelo son</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Talla ~ LRM_R + Edad + Sexo, family = Gamma(), 
    data = datos)

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    1.002e-02  1.436e-04  69.770  &lt; 2e-16 ***
LRM_R         -8.954e-05  2.980e-06 -30.045  &lt; 2e-16 ***
Edad           4.103e-06  1.079e-06   3.802 0.000164 ***
SexoMasculino -1.579e-04  2.019e-05  -7.819 4.14e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for Gamma family taken to be 0.0005437082)

    Null deviance: 1.57735  on 434  degrees of freedom
Residual deviance: 0.23567  on 431  degrees of freedom
AIC: 2366.2

Number of Fisher Scoring iterations: 3</code></pre>
</div>
</div>
<p>Entonces, la ecuación propuesta por este modelo para estimar el logaritmo de la talla en adultos mayores es:</p>
<p><span class="math display">\[\ln(Talla) = 9.972e-03 - 8.941e-05 LRM\_R + 4.774e-06 Edad - 1.618e-04 Sexo\]</span><br>
<span class="math display">\[Sexo = \begin{cases} 1 &amp; \text{si sexo = Masculino} \\ 0 &amp; \text{si sexo = Femenino} \end{cases}\]</span><br>
</p>
<p>Se utiliza el método de<strong><em>k-fold cross validation</em></strong> con <span class="math inline">\(k = 10\)</span> y y se calcula el promedio del MSE obtenido en cada iteración. El MSE para este modelo es:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 13.1695</code></pre>
</div>
</div>
</section>
<section id="lrm-pierna-90" class="level3">
<h3 class="anchored" data-anchor-id="lrm-pierna-90">LRM pierna 90°</h3>
<p>Inicialmente, se ajusta el modelo Gamma que incluye a todas las variables regresoras que se cree influyen en la estimación de la talla.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Talla ~ LRM_90 + Edad + Etnia + Sexo, family = Gamma(), 
    data = datos)

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)          1.018e-02  1.641e-04  62.017  &lt; 2e-16 ***
LRM_90              -8.885e-05  2.989e-06 -29.728  &lt; 2e-16 ***
Edad                 4.076e-06  1.087e-06   3.749 0.000202 ***
EtniaBlanco-Mestizo -9.746e-05  7.367e-05  -1.323 0.186574    
EtniaIndigena       -1.293e-04  9.752e-05  -1.326 0.185459    
EtniaRrom           -1.580e-04  1.562e-04  -1.012 0.312337    
SexoMasculino       -2.046e-04  1.927e-05 -10.619  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for Gamma family taken to be 0.0005481876)

    Null deviance: 1.57735  on 434  degrees of freedom
Residual deviance: 0.23564  on 428  degrees of freedom
AIC: 2372.1

Number of Fisher Scoring iterations: 3</code></pre>
</div>
</div>
<p>A continuación se realiza una selección de variables con el método “forward” de tal forma que se minimice el AIC. El modelo seleccionado resulta ser el que incluye Edad, Sexo y LRT_A.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=3187.34
Talla ~ 1

         Df Deviance    AIC
+ LRM_90  1  0.30077 2836.8
+ Sexo    1  0.73444 2956.6
&lt;none&gt;       1.57735 3187.3
+ Edad    1  1.57197 3187.9
+ Etnia   3  1.56020 3188.6

Step:  AIC=2468.26
Talla ~ LRM_90

        Df Deviance    AIC
+ Sexo   1  0.24419 2388.7
+ Edad   1  0.29828 2466.7
&lt;none&gt;      0.30077 2468.3
+ Etnia  3  0.30011 2473.3

Step:  AIC=2379.61
Talla ~ LRM_90 + Sexo

        Df Deviance    AIC
+ Edad   1  0.23686 2368.6
&lt;none&gt;      0.24419 2379.6
+ Etnia  3  0.24335 2384.1

Step:  AIC=2368.33
Talla ~ LRM_90 + Sexo + Edad

        Df Deviance    AIC
&lt;none&gt;      0.23686 2368.3
+ Etnia  3  0.23564 2372.1</code></pre>
</div>
</div>
<p>Los coeficientes del modelo son</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Talla ~ LRM_90 + Edad + Sexo, family = Gamma(), 
    data = datos)

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    1.009e-02  1.463e-04   68.96  &lt; 2e-16 ***
LRM_90        -8.884e-05  2.972e-06  -29.90  &lt; 2e-16 ***
Edad           3.964e-06  1.083e-06    3.66 0.000284 ***
SexoMasculino -2.038e-04  1.924e-05  -10.60  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for Gamma family taken to be 0.0005471928)

    Null deviance: 1.57735  on 434  degrees of freedom
Residual deviance: 0.23686  on 431  degrees of freedom
AIC: 2368.3

Number of Fisher Scoring iterations: 3</code></pre>
</div>
</div>
<p>Entonces, la ecuación propuesta por este modelo para estimar el logaritmo de la talla en adultos mayores es:</p>
<p><span class="math display">\[\ln(Talla) = 1.005e-02 - 8.939e-05 LRT\_A + 4.792e-06 Edad - 2.022e-04 Sexo\]</span><br>
<span class="math display">\[Sexo = \begin{cases} 1 &amp; \text{si sexo = Masculino} \\ 0 &amp; \text{si sexo = Femenino} \end{cases}\]</span><br>
</p>
<p>Se utiliza el método de<strong><em>k-fold cross validation</em></strong> con <span class="math inline">\(k = 10\)</span> y y se calcula el promedio del MSE obtenido en cada iteración. El MSE para este modelo es:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 13.19002</code></pre>
</div>
</div>
</section>
<section id="resumen-modelos-gamma" class="level3">
<h3 class="anchored" data-anchor-id="resumen-modelos-gamma">Resumen modelos Gamma</h3>
<p>En general, los modelos Gamma ajustados incluyeron las mismas tres variables del modelo normal (edad, sexo y mediciones). Cada modelo produjo diferentes estimaciones para los parámetros, lo que resulta en ecuaciones distintas para estimar la talla de los adultos mayores.</p>
<p>De nuevo, es preferible el modelo Gamma que tenga menor error cuadrático medio. Y en general, es preferible el modelo (normal, LASSO o Gamma) que tenga menor MSE.</p>
<p>La tabla de los errores cuadráticos medios de los modelos ajustados hasta el momento es:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   Modelo Medida      MSE
1  Normal  LRT_A 10.14466
2  Normal LRT_CM 11.52624
3  Normal  LRM_R 12.83537
4  Normal LRM_90 12.97915
5   LASSO  LRT_A 10.18571
6   LASSO LRT_CM 11.54195
7   LASSO  LRM_R 12.82789
8   LASSO LRM_90 13.00511
9   Gamma  LRT_A 10.64520
10  Gamma LRT_CM 11.86227
11  Gamma  LRM_R 13.16950
12  Gamma LRM_90 13.19002</code></pre>
</div>
</div>
<p>El modelo normal con LRT_A sigue siendo el mejor, ya que hasta el momento es el que presenta el menor MSE. Por lo tanto, no se procederá a verificar los supuestos para ninguno de los modelos Gamma, dado que el modelo normal continúa siendo superior.</p>
</section>
</section>
<section id="propuesta-nuevas-fórmulas" class="level2">
<h2 class="anchored" data-anchor-id="propuesta-nuevas-fórmulas">Propuesta: Nuevas fórmulas</h2>
<p>Dado que el modelo ajustado con menor error cuadrático medio es el normal con LRT con antropómetro, la fórmula que se propone en esta investigación para realizar la estimación de la talla de adultos mayores en Colombia es</p>
<p><span class="math display">\[Talla = 59.11 + 2.19 LRT\_A - 0.12 Edad + 3.06 Sexo\]</span><br>
<span class="math display">\[Sexo = \begin{cases} 1 &amp; \text{si sexo = masculino} \\ 0 &amp; \text{si sexo = femenino} \end{cases}\]</span></p>
<p>Que también puede verse como dos fórmulas, una para cada sexo:</p>
<ul>
<li>Sexo masculino: <span class="math inline">\(Talla = 62.17 + 2.19 LRT\_A - 0.12 Edad\)</span>, la interpretación de cada parámetro es:
<ul>
<li>Intercepto: Suponiendo el caso hipotético en que un adulto mayor tenga <span class="math inline">\(LRT\_A = 0\)</span> y <span class="math inline">\(Edad = 0\)</span>, entonces la talla estimada para ese adulto mayor de sexo masculino es <span class="math inline">\(62.17cm\)</span>.</li>
<li>LRT_A: Por cada centímetro adicional que mida la LRT_A del adulto mayor masculino, entonces la estimación de su talla aumenta <span class="math inline">\(2.19\)</span> centímetros.</li>
<li>Edad: Por cada año cumplido adicional que tenga el adulto mayor de sexo masculino, la estimación de su talla disminuye <span class="math inline">\(0.12cm\)</span>.</li>
</ul></li>
<li>Sexo femenino: <span class="math inline">\(Talla = 59.11 + 2.19 LRT\_A - 0.12 Edad\)</span>, la interpretación de cada parámetro es:
<ul>
<li>Intercepto: Suponiendo el caso hipotético en que un adulto mayor tenga <span class="math inline">\(LRT\_A = 0\)</span> y <span class="math inline">\(Edad = 0\)</span>, entonces la talla estimada para ese adulto mayor de sexo femenino es <span class="math inline">\(59.11\)</span>.</li>
<li>LRT_A: Por cada centímetro adicional que mida la LRT_A del adulto mayor femenino, entonces la estimación de su talla aumenta <span class="math inline">\(2.19\)</span> centímetros.</li>
<li>Edad: Por cada año cumplido adicional que tenga el adulto mayor de sexo femenino, la estimación de su talla disminuye <span class="math inline">\(0.12cm\)</span>.</li>
</ul></li>
</ul>
</section>
<section id="fórmulas-benjumea" class="level2">
<h2 class="anchored" data-anchor-id="fórmulas-benjumea">Fórmulas Benjumea</h2>
<p>Se calculan las estimaciones de las tallas a partir de las fórmulas de Benjumea, esto para compararlas con las estimaciones de la fórmula propuesta en esta investigación.</p>
<p>Las fórmulas de Benjumea son:</p>
<ul>
<li><p>Indígena masculino: <span class="math inline">\(82.695 + 1.745 LRT_A - 0.121 Edad\)</span></p></li>
<li><p>Indígena femenino: <span class="math inline">\(90.281 + 1.436 LRT_A - 0.102 Edad\)</span></p></li>
<li><p>Afrodescendiente masculino: <span class="math inline">\(9.298 + 1.855 LRT_A - 0.141 Edad\)</span></p></li>
<li><p>Afrodescendiente femenino: <span class="math inline">\(76.233 + 1.767 LRT_A - 0.098 Edad\)</span></p></li>
<li><p>Blanco-Mestizo masculino: <span class="math inline">\(75.514 + 1.883 LRT_A - 0.108 Edad\)</span></p></li>
<li><p>Blanco-Mestizo femenino: <span class="math inline">\(86.497 + 1.553 LRT_A - 0.119 Edad\)</span></p></li>
</ul>
<p>Cabe resaltar que no existe fórmula para la etnia Rrom, por lo que hubo un individuo en la muestra a quien no fue posible realizar la estimación por medio de las fórmulas de Benjumea.</p>
<section id="lrt-antropómetro-3" class="level3">
<h3 class="anchored" data-anchor-id="lrt-antropómetro-3">LRT Antropómetro</h3>
<p>Las fórmulas de Benjumea tienen en cuenta la medición LRT. El error cuadrático medio de las fórmulas de Benjumea con LRT_A es</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12.69694</code></pre>
</div>
</div>
</section>
<section id="lrt-cinta-métrica-3" class="level3">
<h3 class="anchored" data-anchor-id="lrt-cinta-métrica-3">LRT cinta métrica</h3>
<p>Las fórmulas de Benjumea tienen en cuenta la medición LRT. El error cuadrático medio de las fórmulas de Benjumea con LRT_CM es</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 14.24937</code></pre>
</div>
</div>
</section>
<section id="resumen-fórmulas-benjumea" class="level3">
<h3 class="anchored" data-anchor-id="resumen-fórmulas-benjumea">Resumen fórmulas Benjumea</h3>
<p>La tabla de los errores cuadráticos medios con las fórmulas de Benjumea es:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>     Modelo Medida      MSE
13 Benjumea  LRT_A 12.69694
14 Benjumea LRT_CM 14.24937</code></pre>
</div>
</div>
<p>Los MSE son mayores a los modelos ajustados anteriormente.</p>
</section>
</section>
<section id="fórmulas-arango-y-zamora" class="level2">
<h2 class="anchored" data-anchor-id="fórmulas-arango-y-zamora">Fórmulas Arango y Zamora</h2>
<p>Se calculan las estimaciones de las tallas a partir de las fórmulas de Arango y Zamora, esto para compararlas con las estimaciones de la fórmula propuesta en esta investigación.</p>
<p>Las fórmulas de Arango y Zamora son:</p>
<ul>
<li>Sexo masculino: <span class="math inline">\(119.6 + 1.121 LRM_R - 0.117 Edad\)</span></li>
<li>Sexo femenino: <span class="math inline">\(107.7 + 1.263 LRM_R - 0.159 Edad\)</span></li>
</ul>
<section id="lrm-pierna-estirada-3" class="level3">
<h3 class="anchored" data-anchor-id="lrm-pierna-estirada-3">LRM pierna estirada</h3>
<p>Las fórmulas de Arango y Zamora tienen en cuenta la medición LRM. El error cuadrático medio de las fórmulas de Arango y Zamora con LRM_R es</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 22.18134</code></pre>
</div>
</div>
</section>
<section id="lrm-pierna-a-90-2" class="level3">
<h3 class="anchored" data-anchor-id="lrm-pierna-a-90-2">LRM pierna a 90°</h3>
<p>Las fórmulas de Arango y Zamora tienen en cuenta la medición LRM. El error cuadrático medio de las fórmulas de Arango y Zamora con LRM_90 es</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 19.60496</code></pre>
</div>
</div>
</section>
<section id="resumen-fórmulas-arango-y-zamora" class="level3">
<h3 class="anchored" data-anchor-id="resumen-fórmulas-arango-y-zamora">Resumen fórmulas Arango y Zamora</h3>
<p>La tabla de los errores cuadráticos medios con las fórmulas de Benjumea es:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>           Modelo Medida      MSE
15 Arango, Zamora  LRM_R 22.18134
16 Arango, Zamora LRM_90 19.60496</code></pre>
</div>
</div>
<p>Los MSE son mayores a los modelos ajustados anteriormente.</p>
</section>
</section>
<section id="conclusión" class="level2">
<h2 class="anchored" data-anchor-id="conclusión">Conclusión</h2>
<p>A continuación, se muestra la tabla de los MSE de todos los modelos ajustados en la investigación y de las fórmulas de Benjumea y de Arango y Zamora.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>           Modelo Medida      MSE
1          Normal  LRT_A 10.14466
2          Normal LRT_CM 11.52624
3          Normal  LRM_R 12.83537
4          Normal LRM_90 12.97915
5           LASSO  LRT_A 10.18571
6           LASSO LRT_CM 11.54195
7           LASSO  LRM_R 12.82789
8           LASSO LRM_90 13.00511
9           Gamma  LRT_A 10.64520
10          Gamma LRT_CM 11.86227
11          Gamma  LRM_R 13.16950
12          Gamma LRM_90 13.19002
13       Benjumea  LRT_A 12.69694
14       Benjumea LRT_CM 14.24937
15 Arango, Zamora  LRM_R 22.18134
16 Arango, Zamora LRM_90 19.60496</code></pre>
</div>
</div>
<p>Se observa que el modelo que presenta menor MSE es el modelo normal con LRT con antropómetro, de modo que, se concluye que este es el mejor modelo pues sus estimaciones de la talla son más cercanas a la verdadera talla del adulto mayor.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Por lo que las fórmulas que mejor estiman la talla de los adultos mayores en Colombia, según la base de datos analizada, son:</p>
<p><span class="math display">\[Talla = 59.11 + 2.19 LRT\_A - 0.12 Edad + 3.06 Sexo\]</span><br>
<span class="math display">\[Sexo = \begin{cases} 1 &amp; \text{si sexo = masculino} \\ 0 &amp; \text{si sexo = femenino} \end{cases}\]</span></p>
</div>
</div>
</section>
<section id="comportamiento-de-las-variables-de-interés-por-subgrupos" class="level2">
<h2 class="anchored" data-anchor-id="comportamiento-de-las-variables-de-interés-por-subgrupos">Comportamiento de las variables de interés por subgrupos</h2>
<section id="sexo-femenino" class="level3">
<h3 class="anchored" data-anchor-id="sexo-femenino">Sexo femenino</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  Variable   n Minimo Maximo  Promedio   DesEst Mediana
1     Edad 218  60.00  88.00  70.63761 6.545260  70.000
2    Talla 218 127.10 163.65 149.37936 6.063146 149.575
3    LRT_A 218  36.85  50.55  45.16078 2.384959  45.200
4   LRT_CM 218  38.00  52.05  46.81674 2.362067  46.900</code></pre>
</div>
</div>
</section>
<section id="sexo-masculino" class="level3">
<h3 class="anchored" data-anchor-id="sexo-masculino">Sexo masculino</h3>
</section>
</section>
<section id="cuadro-modelos-predicción-de-la-talla-por-sexo" class="level2">
<h2 class="anchored" data-anchor-id="cuadro-modelos-predicción-de-la-talla-por-sexo">Cuadro Modelos predicción de la talla por sexo</h2>
<section id="opción-1-modelo-normal-lrt_a" class="level3">
<h3 class="anchored" data-anchor-id="opción-1-modelo-normal-lrt_a">Opción 1: Modelo normal LRT_A</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>      n        R2       EE Normalidad Homocedasticidad
BP  218 0.7303663 3.141136  0.2926674        0.8010954
BP1 217 0.7804718 3.153099  0.9472230        0.1386984</code></pre>
</div>
</div>
</section>
<section id="opción-2-modelo-normal-lrt_cm" class="level3">
<h3 class="anchored" data-anchor-id="opción-2-modelo-normal-lrt_cm">Opción 2: Modelo normal LRT_CM</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>      n        R2       EE Normalidad Homocedasticidad
BP  218 0.6930547 3.351430 0.07928016       0.14221501
BP1 217 0.7521653 3.350222 0.39498815       0.01975212</code></pre>
</div>
</div>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>