<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>modelos</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Ninguna coincidencia",
    "search-matching-documents-text": "coincidencias",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Inicio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./descriptivo.html"> 
<span class="menu-text">Análisis descriptivo</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./hipotesis.html"> 
<span class="menu-text">Evaluación de hipótesis</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./modelos.html" aria-current="page"> 
<span class="menu-text">Modelos</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenido</h2>
   
  <ul>
  <li><a href="#modelos" id="toc-modelos" class="nav-link active" data-scroll-target="#modelos">Modelos</a>
  <ul>
  <li><a href="#selección-del-mejor-modelo-usando-lrt_a" id="toc-selección-del-mejor-modelo-usando-lrt_a" class="nav-link" data-scroll-target="#selección-del-mejor-modelo-usando-lrt_a">Selección del mejor modelo usando LRT_A</a></li>
  <li><a href="#modelo-normal" id="toc-modelo-normal" class="nav-link" data-scroll-target="#modelo-normal">Modelo normal</a>
  <ul class="collapse">
  <li><a href="#lrt-antropómetro" id="toc-lrt-antropómetro" class="nav-link" data-scroll-target="#lrt-antropómetro">LRT Antropómetro</a></li>
  <li><a href="#lrt-cinta-métrica" id="toc-lrt-cinta-métrica" class="nav-link" data-scroll-target="#lrt-cinta-métrica">LRT cinta métrica</a></li>
  <li><a href="#lrm-pierna-estirada" id="toc-lrm-pierna-estirada" class="nav-link" data-scroll-target="#lrm-pierna-estirada">LRM pierna estirada</a></li>
  <li><a href="#lrm-pierna-a-90" id="toc-lrm-pierna-a-90" class="nav-link" data-scroll-target="#lrm-pierna-a-90">LRM pierna a 90°</a></li>
  <li><a href="#resúmen-de-los-modelos-normales." id="toc-resúmen-de-los-modelos-normales." class="nav-link" data-scroll-target="#resúmen-de-los-modelos-normales.">Resúmen de los modelos normales.</a></li>
  </ul></li>
  <li><a href="#modelo-lasso" id="toc-modelo-lasso" class="nav-link" data-scroll-target="#modelo-lasso">Modelo Lasso</a></li>
  <li><a href="#lasso-sin-tener-en-cuenta-lrt_a" id="toc-lasso-sin-tener-en-cuenta-lrt_a" class="nav-link" data-scroll-target="#lasso-sin-tener-en-cuenta-lrt_a">Lasso sin tener en cuenta LRT_A</a></li>
  <li><a href="#modelo-lasso-1" id="toc-modelo-lasso-1" class="nav-link" data-scroll-target="#modelo-lasso-1">Modelo Lasso</a>
  <ul class="collapse">
  <li><a href="#lrt-antropómetro-1" id="toc-lrt-antropómetro-1" class="nav-link" data-scroll-target="#lrt-antropómetro-1">LRT Antropómetro</a></li>
  <li><a href="#lrt-cinta-métrica-1" id="toc-lrt-cinta-métrica-1" class="nav-link" data-scroll-target="#lrt-cinta-métrica-1">LRT cinta métrica</a></li>
  <li><a href="#lrm-pierna-estirada-1" id="toc-lrm-pierna-estirada-1" class="nav-link" data-scroll-target="#lrm-pierna-estirada-1">LRM pierna estirada</a></li>
  <li><a href="#lrm-pierna-a-90-1" id="toc-lrm-pierna-a-90-1" class="nav-link" data-scroll-target="#lrm-pierna-a-90-1">LRM pierna a 90°</a></li>
  </ul></li>
  <li><a href="#modelo-gamma" id="toc-modelo-gamma" class="nav-link" data-scroll-target="#modelo-gamma">Modelo Gamma</a></li>
  <li><a href="#modelo-gamma-1" id="toc-modelo-gamma-1" class="nav-link" data-scroll-target="#modelo-gamma-1">Modelo Gamma</a>
  <ul class="collapse">
  <li><a href="#lrt-antropómetro-2" id="toc-lrt-antropómetro-2" class="nav-link" data-scroll-target="#lrt-antropómetro-2">LRT Antropómetro</a></li>
  <li><a href="#lrt-cinta-métrica-2" id="toc-lrt-cinta-métrica-2" class="nav-link" data-scroll-target="#lrt-cinta-métrica-2">LRT cinta métrica</a></li>
  <li><a href="#lrm-pierna-estirada-2" id="toc-lrm-pierna-estirada-2" class="nav-link" data-scroll-target="#lrm-pierna-estirada-2">LRM pierna estirada</a></li>
  <li><a href="#lrm-pierna-90" id="toc-lrm-pierna-90" class="nav-link" data-scroll-target="#lrm-pierna-90">LRM pierna 90°</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-page-left" id="quarto-document-content">




<section id="modelos" class="level1">
<h1>Modelos</h1>
<p>A continuación el resumen de la evaluación de las hipótesis de interés:</p>
<ul>
<li>La diferencia en las mediciones de LRT con antropómetro y con cinta métrica resultó ser estadísticamente significativa.</li>
<li>La diferencia en las mediciones de LRM con la pierna a <span class="math inline">\(90°\)</span> y la pierna estirada resultó ser estadísticamente significativa.</li>
</ul>
<p>Estos resultados sigieren que:</p>
<ul>
<li>No es posible determinar que las mediciones de LRT con la cinta métrica sean iguales a las obtenidas con antropómetro. Asumiendo que la medición con antropómetro es más exacta, las mediciones con la cinta métrica suelen sobreestimar en promedio a las del antropómetro.</li>
<li>Tampoco es posible determinar que las mediciones de LRM con la pierna a <span class="math inline">\(90°\)</span> y con la pierna estirada sean iguales. La medición con la pierna estirada suele ser en promedio menor a la medición hecha con la pierna a <span class="math inline">\(90°\)</span>.</li>
</ul>
<p>Los resultados obtenidos al evaluar las fórmulas de <strong><em>Benjumea</em></strong> y de <strong><em>Arango y Zamora</em></strong> en muestra de adultos mayores que atiende la SDIS, parecen no tener muy buenos resultados a la hora de estimar la talla de los adultos mayores.</p>
<p>Dado estos resultados, se concluye que se requiere de fórmulas específicas para la población que atiende la <strong>SDIS</strong>. Además, se deberá ajustar estos modelos para las cuatro mediciones pues la evaluación de las hipótesis no dieron indicios de la igualdad entre los métodos de las mediciones.</p>
<section id="selección-del-mejor-modelo-usando-lrt_a" class="level2">
<h2 class="anchored" data-anchor-id="selección-del-mejor-modelo-usando-lrt_a">Selección del mejor modelo usando LRT_A</h2>
<p>Inicialmente, se hará la selección del mejor modelo para LRT_A mediante un enfoque predictivo.</p>
<p>A continuación se hace una búsqueda del mejor modelo por cada número de posibles combinaciones de variables. Primero se hará la búsqueda usando todo el conjunto de datos.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Subset selection object
Call: regsubsets.formula(Talla ~ LRT_A + Peso + Edad + Sexo + Etnia + 
    Programa, datos, nbest = 1, nvmax = 10)
8 Variables  (and intercept)
                             Forced in Forced out
LRT_A                            FALSE      FALSE
Peso                             FALSE      FALSE
Edad                             FALSE      FALSE
SexoMasculino                    FALSE      FALSE
EtniaBlanco-Mestizo              FALSE      FALSE
EtniaIndigena                    FALSE      FALSE
EtniaRrom                        FALSE      FALSE
ProgramaComunidad de Cuidado     FALSE      FALSE
1 subsets of each size up to 8
Selection Algorithm: exhaustive
         LRT_A Peso Edad SexoMasculino EtniaBlanco-Mestizo EtniaIndigena
1  ( 1 ) "*"   " "  " "  " "           " "                 " "          
2  ( 1 ) "*"   " "  " "  "*"           " "                 " "          
3  ( 1 ) "*"   " "  "*"  "*"           " "                 " "          
4  ( 1 ) "*"   "*"  "*"  "*"           " "                 " "          
5  ( 1 ) "*"   " "  "*"  "*"           "*"                 "*"          
6  ( 1 ) "*"   " "  "*"  "*"           "*"                 "*"          
7  ( 1 ) "*"   "*"  "*"  "*"           "*"                 "*"          
8  ( 1 ) "*"   "*"  "*"  "*"           "*"                 "*"          
         EtniaRrom ProgramaComunidad de Cuidado
1  ( 1 ) " "       " "                         
2  ( 1 ) " "       " "                         
3  ( 1 ) " "       " "                         
4  ( 1 ) " "       " "                         
5  ( 1 ) " "       " "                         
6  ( 1 ) "*"       " "                         
7  ( 1 ) "*"       " "                         
8  ( 1 ) "*"       "*"                         </code></pre>
</div>
</div>
<p><span class="math inline">\(R^2\)</span>, <span class="math inline">\(R^2\)</span> ajustado, SCE, y BIC para cada mejor modelo del correspondiente tamaño:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8686814 0.8789431 0.8862590 0.8865490 0.8869361 0.8873216 0.8875270
[8] 0.8875271</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8684386 0.8784947 0.8856260 0.8857055 0.8858834 0.8860602 0.8860554
[8] 0.8858421</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6398.986 5898.947 5542.449 5528.321 5509.455 5490.674 5480.665 5480.657</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1089.766 -1127.650 -1155.202 -1150.291 -1145.850 -1141.407 -1136.101
[8] -1129.804</code></pre>
</div>
</div>
<p>Usando el criterio BIC, el mejor modelo es el de 3 variables:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelos_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelos_files/figure-html/unnamed-chunk-5-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Usando el <span class="math inline">\(R^2\)</span> ajustado, se sugiere un modelo con 5 variables:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelos_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Los coeficientes del mejor modelo usando el criterio de BIC son:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)         LRT_A          Edad SexoMasculino 
   59.1083106     2.1894102    -0.1216628     3.0653353 </code></pre>
</div>
</div>
<p>Esto sugiere usar el modelo <span class="math inline">\(Talla = 58.67 + 2.19 LRT\_A - 0.12Edad + 3.06Sexo\)</span>,<br>
<span class="math display">\[Sexo = \begin{cases} 1 &amp; \text{si sexo = hombre} \\ 0 &amp; \text{si sexo = mujer} \end{cases}\]</span></p>
<p>Ahora se hará la búsqueda del mejor modelo usando <strong><em>K - fold cross validation</em></strong> con el fin de calcular directamente los errores de predicción sobre los datos de testeo y evitar así el sobreajuste.</p>
<ul>
<li>Se crean <strong><em>K - folds</em></strong> (pliegues) de aproximadamente igual tamaño. En este caso fijamos <span class="math inline">\(k = 10\)</span>. Como tenemos <span class="math inline">\(558\)</span> datos, cada pliegue será de tamaño 55 o 56.</li>
<li>El <span class="math inline">\(k-ésimo\)</span> pliegue servirá para testear, y los demás pliegues se juntan para entrenar los modelos. Osea que se usará un <span class="math inline">\(90\%\)</span> de los datos para entrenamiento y <span class="math inline">\(10\%\)</span> para test.</li>
<li>Para <span class="math inline">\(k = 1,\cdots,10,\)</span> se hace la búsqueda del mejor modelo para cada número de variables y se calcula el MSE.</li>
<li>Luego, se promedia el MSE a través de los <span class="math inline">\(10\)</span> pliegues y se escoge el tamaño de modelo con menor MSE promedio.</li>
<li>Finalmente, se hace la búsqueda del mejor modelo por cada número de variables usando todos los datos disponibles y se escoge el modelo asociado al tamaño del modelo obtenido en la validación cruzada.</li>
</ul>
<p>Tamaño de los pliegues:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>folds
 1  2  3  4  5  6  7  8  9 10 
55 55 55 54 54 54 54 54 54 54 </code></pre>
</div>
</div>
<p>MSE promedio a través de los <span class="math inline">\(10\)</span> pliegues para cada número de variables incluídas en el modelo:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Reordering variables and trying again:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2        3        4        5        6        7 
11.88403 11.00914 10.39225 10.47051 10.55927 10.61288 10.55258 </code></pre>
</div>
</div>
<p>El MSE se minimiza usando un modelo de 3 variables:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelos_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Se busca nuevamente el mejor modelo de tres variables usando todos los datos:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1089.766 -1127.650 -1155.202 -1150.291 -1145.850 -1141.407 -1136.101
[8] -1129.804</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)         LRT_A          Edad SexoMasculino 
   59.1083106     2.1894102    -0.1216628     3.0653353 </code></pre>
</div>
</div>
<p>Casualmente volvió a dar el mismo modelo con tres variables que incluye LRT_A, la Edad y el Sexo. Esto es seguramente porque las demás variables no contribuyen significativamente a la presición predictiva de los modelos.</p>
<p>Ahora se validarán los supuestos para el mejor modelo obtenido:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Talla ~ LRT_A + Edad + Sexo, data = datos)

Residuals:
     Min       1Q   Median       3Q      Max 
-10.4374  -2.0311   0.1058   2.2783   9.2680 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   59.10831    2.90260  20.364  &lt; 2e-16 ***
LRT_A          2.18941    0.05360  40.848  &lt; 2e-16 ***
Edad          -0.12166    0.02066  -5.888 6.88e-09 ***
SexoMasculino  3.06534    0.38877   7.885 1.76e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.207 on 539 degrees of freedom
Multiple R-squared:  0.8863,    Adjusted R-squared:  0.8856 
F-statistic:  1400 on 3 and 539 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>El modelo tiene un <span class="math inline">\(R^2\)</span> ajustado de <span class="math inline">\(0.8861\)</span>, es decir que aproximadamente un <span class="math inline">\(88.61\%\)</span> de la variabilidad de la talla es explicada por LRT_A, la edad y el sexo.</p>
<p><strong><em>Linealidad:</em></strong> Con el fin de verificar que la relación entre la talla y las variables LRT_A (discriminando por sexo) y la edad es lineal, se visualiza el gráfico de los residuos vs los valores predichos del modelo <span class="math inline">\(\left(\hat{e},\hat{y} \right)\)</span>:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelos_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El gráfico no muestra ningún patrón marcado, la ubicación de los puntos parece ser aleatoria alrededor de cero, indicando también homoscedasticidad en los residuales y posible independencia de los mismos. El gráfico muestra algunos valores atípicos que valdría la pena explorar.</p>
<p><strong><em>Independencia de los errores:</em></strong> Aunque nuestros datos no son temporales, el test de Durbin-Watson nos puede ayudar a evaluar la autocorrelación de los errores del modelo:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Durbin-Watson test

data:  reg
DW = 2.0507, p-value = 0.7173
alternative hypothesis: true autocorrelation is greater than 0</code></pre>
</div>
</div>
<p>La estadística del test de Durbin-Watson es muy cercano a <span class="math inline">\(2\)</span>, se concluye que los errores son independientes.</p>
<p><strong><em>Normalidad de los errores:</em></strong> Se realiza el gráfico QQ-plot para comparar la distribución de los residuales del modelo con la distribución teórica de una normal. También se hace el test de normalidad de Lilliefors y Anderson-Darling:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelos_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Lilliefors (Kolmogorov-Smirnov) normality test

data:  reg$residuals
D = 0.02184, p-value = 0.7651</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Anderson-Darling normality test

data:  reg$residuals
A = 0.41295, p-value = 0.337</code></pre>
</div>
</div>
<p>El QQ-plot muestra que los residuales se ajustan aceptablemente a una distribución normal. Las pruebas de normalidad de Lilliefors y Anderson-Darling también apoyan este resultado.</p>
<p><strong><em>Homoscedasticidad:</em></strong> Aunque no se vio un patron que indicara heteroscedasticidad en el gráfico de los residuales vs los valores predichos, a continuación se muestra el gráfico de los residuales estandarizados vs los valores predichos con el fin de mejorar la interpretabilidad de la homoscedasticidad y tener una visión más clara de las observaciones atípicas e influyentes:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelos_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>No se observan patrones que indiquen hereroscedasticidad en los residuos (forma de cono o embudo). Se siguien observando algunas observaciones atípicas y/o influyentes.</p>
<p>Adicional, se realiza la prueba de Breusch-Pagan para verificar la homoscedasticidad de los residuales:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    studentized Breusch-Pagan test

data:  reg
BP = 0.8348, df = 3, p-value = 0.8411</code></pre>
</div>
</div>
<p>No se rechaza la hipótesis nula de que los errores del modelo son homoscedasticos.</p>
<p><strong><em>Multicolinealidad:</em></strong> Se verifica que las variables incluídas en el modelo no están altamente correlacionadas entre sí, y así evitar obtener resultados inestables que dificulten la interpretabilidad de los coeficientes del modelo. Se calculan los Factores de Inflación de la Varianza (VIFs):</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   LRT_A     Edad     Sexo 
1.942637 1.038371 1.995345 </code></pre>
</div>
</div>
<p>Dado que los VIFs son mucho menores a 5, esto indica que cada variable tiene una correlación moderada (leve) con las demás. Por lo que se puede concluir que los resultados del modelo posiblemente no estarán muy afectados por la multicolinealidad.</p>
<p><strong><em>El modelo está bien especificado:</em></strong> Se hace el test de RESET para examinar si el modelo ajustado está bien especificado o si se han omitido términos no lineales o interacciones importantes:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    RESET test

data:  reg
RESET = 0.62101, df1 = 4, df2 = 535, p-value = 0.6477</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    RESET test

data:  reg
RESET = 0.98691, df1 = 2, df2 = 537, p-value = 0.3734</code></pre>
</div>
</div>
<p>No se rechaza la hipótesis nula de que el modelo está bien especificado.</p>
<p><strong><em>Obervaciones atípicas y de alto apalancamiento:</em></strong></p>
<div>

</div>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="modelos_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="modelos_files/figure-html/unnamed-chunk-20-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
<p>Usando los residuales estudentizados, se observan <span class="math inline">\(5\)</span> datos atípicos.</p>
<div>

</div>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="modelos_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="modelos_files/figure-html/unnamed-chunk-21-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="quarto-layout-row">
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>       StudRes        Hat       CookD
41  -2.9464281 0.01514476 0.032906079
505 -0.6485772 0.03066342 0.003330247
520 -3.3029648 0.01104953 0.029923010
538 -0.8302135 0.02463562 0.004354784</code></pre>
</div>
</div>
</div>
<p>En total 29 observaciones superan el umbral especificado para la distancia de Cook, pero esto no significa que todas sean influyentes (alto leverage). Particularmente hay 3 observaciones que son marcadas como influyentes significativamente según la distancia de Cook. Esto indica que la inclusión de estas observaciones en el modelo pueden tener una influencia significativa en los coeficientes del modelo y en la predicción de la talla. Se debe explorar con cautela estas observaciones y decidir qué hacer con ellas.</p>
<p>Para esto, se puede comprobar el cambio en los coeficientes del modelo al excluir estas observaciones influyentes.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Talla ~ LRT_A + Edad + Sexo, data = datos, subset = {
    setdiff(row(datos)[, 1], c(533, 43, 549))
})

Residuals:
     Min       1Q   Median       3Q      Max 
-10.4573  -2.0353   0.1184   2.2692   9.2417 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   59.22121    2.91027  20.349  &lt; 2e-16 ***
LRT_A          2.18636    0.05401  40.477  &lt; 2e-16 ***
Edad          -0.12112    0.02073  -5.843 8.88e-09 ***
SexoMasculino  3.07005    0.38910   7.890 1.70e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.208 on 537 degrees of freedom
Multiple R-squared:  0.8846,    Adjusted R-squared:  0.8839 
F-statistic:  1372 on 3 and 537 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Las estimaciones de los coeficientes del modelo sin las obervaciones influyentes han cambiado un poco respecto al modelo original. El <span class="math inline">\(R^2\)</span> ajustado ha incrementado un poco también.</p>
</section>
<section id="modelo-normal" class="level2">
<h2 class="anchored" data-anchor-id="modelo-normal">Modelo normal</h2>
<section id="lrt-antropómetro" class="level3">
<h3 class="anchored" data-anchor-id="lrt-antropómetro">LRT Antropómetro</h3>
<p>A continuación se hace una búsqueda del mejor modelo por cada número de posibles combinaciones de variables de las cuales se tenga evidencia que influyen en la talla de adultos mayores. Primero se hará la búsqueda usando todo el conjunto de datos.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Subset selection object
Call: regsubsets.formula(Talla ~ LRT_A + Edad + Sexo + Etnia, datos, 
    nbest = 1, nvmax = 10)
6 Variables  (and intercept)
                    Forced in Forced out
LRT_A                   FALSE      FALSE
Edad                    FALSE      FALSE
SexoMasculino           FALSE      FALSE
EtniaBlanco-Mestizo     FALSE      FALSE
EtniaIndigena           FALSE      FALSE
EtniaRrom               FALSE      FALSE
1 subsets of each size up to 6
Selection Algorithm: exhaustive
         LRT_A Edad SexoMasculino EtniaBlanco-Mestizo EtniaIndigena EtniaRrom
1  ( 1 ) "*"   " "  " "           " "                 " "           " "      
2  ( 1 ) "*"   " "  "*"           " "                 " "           " "      
3  ( 1 ) "*"   "*"  "*"           " "                 " "           " "      
4  ( 1 ) "*"   "*"  "*"           " "                 "*"           " "      
5  ( 1 ) "*"   "*"  "*"           "*"                 "*"           " "      
6  ( 1 ) "*"   "*"  "*"           "*"                 "*"           "*"      </code></pre>
</div>
</div>
<p><span class="math inline">\(R^2\)</span>, <span class="math inline">\(R^2\)</span> ajustado, SCE, y BIC para cada mejor modelo del correspondiente tamaño:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8686814 0.8789431 0.8862590 0.8863940 0.8869361 0.8873216</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8684386 0.8784947 0.8856260 0.8855493 0.8858834 0.8860602</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6398.986 5898.947 5542.449 5535.875 5509.455 5490.674</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1089.766 -1127.650 -1155.202 -1149.550 -1145.850 -1141.407</code></pre>
</div>
</div>
<p>Usando el criterio BIC, el mejor modelo es el de 3 variables:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelos_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelos_files/figure-html/unnamed-chunk-25-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Los coeficientes del mejor modelo usando el criterio de BIC son:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)         LRT_A          Edad SexoMasculino 
   59.1083106     2.1894102    -0.1216628     3.0653353 </code></pre>
</div>
</div>
<p>Esto sugiere usar el modelo <span class="math inline">\(Talla = 58.67 + 2.19 LRT\_A - 0.12Edad + 3.06Sexo\)</span>,<br>
<span class="math display">\[Sexo = \begin{cases} 1 &amp; \text{si sexo = hombre} \\ 0 &amp; \text{si sexo = mujer} \end{cases}\]</span></p>
<p>Ahora se hará la búsqueda del mejor modelo usando <strong><em>K - fold cross validation</em></strong> con el fin de calcular directamente los errores de predicción sobre los datos de testeo y evitar así el sobreajuste.</p>
<ul>
<li>Se crean <strong><em>K - folds</em></strong> (pliegues) de aproximadamente igual tamaño. En este caso fijamos <span class="math inline">\(k = 10\)</span>. Como tenemos <span class="math inline">\(558\)</span> datos, cada pliegue será de tamaño 55 o 56.</li>
<li>El <span class="math inline">\(k-ésimo\)</span> pliegue servirá para testear, y los demás pliegues se juntan para entrenar los modelos. Osea que se usará un <span class="math inline">\(90\%\)</span> de los datos para entrenamiento y <span class="math inline">\(10\%\)</span> para test.</li>
<li>Para <span class="math inline">\(k = 1,\cdots,10,\)</span> se calcula el MSE.</li>
<li>Luego, se promedia el MSE a través de los <span class="math inline">\(10\)</span> pliegues y se obtiene el MSE promedio.</li>
</ul>
<p>El MSE para el modelo de 3 variables (<span class="math inline">\(LRT\_A, Edad, Sexo\)</span>) es:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10.39225</code></pre>
</div>
</div>
<p>Ahora se validarán los supuestos para el mejor modelo obtenido:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Talla ~ LRT_A + Edad + Sexo, data = datos)

Residuals:
     Min       1Q   Median       3Q      Max 
-10.4374  -2.0311   0.1058   2.2783   9.2680 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   59.10831    2.90260  20.364  &lt; 2e-16 ***
LRT_A          2.18941    0.05360  40.848  &lt; 2e-16 ***
Edad          -0.12166    0.02066  -5.888 6.88e-09 ***
SexoMasculino  3.06534    0.38877   7.885 1.76e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.207 on 539 degrees of freedom
Multiple R-squared:  0.8863,    Adjusted R-squared:  0.8856 
F-statistic:  1400 on 3 and 539 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>El modelo tiene un <span class="math inline">\(R^2\)</span> ajustado de <span class="math inline">\(0.8861\)</span>, es decir que aproximadamente un <span class="math inline">\(88.61\%\)</span> de la variabilidad de la talla es explicada por LRT_A, la edad y el sexo.</p>
<p><strong><em>Linealidad:</em></strong> Con el fin de verificar que la relación entre la talla y las variables LRT_A (discriminando por sexo) y la edad es lineal, se visualiza el gráfico de los residuos vs los valores predichos del modelo <span class="math inline">\(\left(\hat{e},\hat{y} \right)\)</span>:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelos_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El gráfico no muestra ningún patrón marcado, la ubicación de los puntos parece ser aleatoria alrededor de cero, indicando también homoscedasticidad en los residuales y posible independencia de los mismos. El gráfico muestra algunos valores atípicos que valdría la pena explorar.</p>
<p><strong><em>Independencia de los errores:</em></strong> Aunque nuestros datos no son temporales, el test de Durbin-Watson nos puede ayudar a evaluar la autocorrelación de los errores del modelo:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Durbin-Watson test

data:  reg
DW = 2.0507, p-value = 0.7173
alternative hypothesis: true autocorrelation is greater than 0</code></pre>
</div>
</div>
<p>La estadística del test de Durbin-Watson es muy cercano a <span class="math inline">\(2\)</span>, se concluye que los errores son independientes.</p>
<p><strong><em>Normalidad de los errores:</em></strong> Se realiza el gráfico QQ-plot para comparar la distribución de los residuales del modelo con la distribución teórica de una normal. También se hace el test de normalidad de Lilliefors y Anderson-Darling:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelos_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Lilliefors (Kolmogorov-Smirnov) normality test

data:  reg$residuals
D = 0.02184, p-value = 0.7651</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Anderson-Darling normality test

data:  reg$residuals
A = 0.41295, p-value = 0.337</code></pre>
</div>
</div>
<p>El QQ-plot muestra que los residuales se ajustan aceptablemente a una distribución normal. Las pruebas de normalidad de Lilliefors y Anderson-Darling también apoyan este resultado.</p>
<p><strong><em>Homoscedasticidad:</em></strong> Aunque no se vio un patron que indicara heteroscedasticidad en el gráfico de los residuales vs los valores predichos, a continuación se muestra el gráfico de los residuales estandarizados vs los valores predichos con el fin de mejorar la interpretabilidad de la homoscedasticidad y tener una visión más clara de las observaciones atípicas e influyentes:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelos_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>No se observan patrones que indiquen hereroscedasticidad en los residuos (forma de cono o embudo). Se siguien observando algunas observaciones atípicas y/o influyentes.</p>
<p>Adicional, se realiza la prueba de Breusch-Pagan para verificar la homoscedasticidad de los residuales:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    studentized Breusch-Pagan test

data:  reg
BP = 0.8348, df = 3, p-value = 0.8411</code></pre>
</div>
</div>
<p>No se rechaza la hipótesis nula de que los errores del modelo son homoscedasticos.</p>
<p><strong><em>Multicolinealidad:</em></strong> Se verifica que las variables incluídas en el modelo no están altamente correlacionadas entre sí, y así evitar obtener resultados inestables que dificulten la interpretabilidad de los coeficientes del modelo. Se calculan los Factores de Inflación de la Varianza (VIFs):</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   LRT_A     Edad     Sexo 
1.942637 1.038371 1.995345 </code></pre>
</div>
</div>
<p>Dado que los VIFs son mucho menores a 5, esto indica que cada variable tiene una correlación moderada (leve) con las demás. Por lo que se puede concluir que los resultados del modelo posiblemente no estarán muy afectados por la multicolinealidad.</p>
<p><strong><em>El modelo está bien especificado:</em></strong> Se hace el test de RESET para examinar si el modelo ajustado está bien especificado o si se han omitido términos no lineales o interacciones importantes:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    RESET test

data:  reg
RESET = 0.62101, df1 = 4, df2 = 535, p-value = 0.6477</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    RESET test

data:  reg
RESET = 0.98691, df1 = 2, df2 = 537, p-value = 0.3734</code></pre>
</div>
</div>
<p>No se rechaza la hipótesis nula de que el modelo está bien especificado.</p>
<p><strong><em>Observaciones atípicas y de alto apalancamiento:</em></strong></p>
<div>

</div>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="modelos_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid" width="672"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="modelos_files/figure-html/unnamed-chunk-37-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
<p>Usando los residuales estudentizados, se observan <span class="math inline">\(5\)</span> datos atípicos.</p>
<div>

</div>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="modelos_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid" width="672"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="modelos_files/figure-html/unnamed-chunk-38-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="quarto-layout-row">
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>       StudRes        Hat       CookD
41  -2.9464281 0.01514476 0.032906079
505 -0.6485772 0.03066342 0.003330247
520 -3.3029648 0.01104953 0.029923010
538 -0.8302135 0.02463562 0.004354784</code></pre>
</div>
</div>
</div>
<p>En total 29 observaciones superan el umbral especificado para la distancia de Cook, pero esto no significa que todas sean influyentes (alto leverage). Particularmente hay 3 observaciones que son marcadas como influyentes significativamente según la distancia de Cook. Esto indica que la inclusión de estas observaciones en el modelo pueden tener una influencia significativa en los coeficientes del modelo y en la predicción de la talla. Se debe explorar con cautela estas observaciones y decidir qué hacer con ellas.</p>
<p>Para esto, se puede comprobar el cambio en los coeficientes del modelo al excluir estas observaciones influyentes.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Talla ~ LRT_A + Edad + Sexo, data = datos, subset = {
    setdiff(row(datos)[, 1], c(533, 43, 549))
})

Residuals:
     Min       1Q   Median       3Q      Max 
-10.4573  -2.0353   0.1184   2.2692   9.2417 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   59.22121    2.91027  20.349  &lt; 2e-16 ***
LRT_A          2.18636    0.05401  40.477  &lt; 2e-16 ***
Edad          -0.12112    0.02073  -5.843 8.88e-09 ***
SexoMasculino  3.07005    0.38910   7.890 1.70e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.208 on 537 degrees of freedom
Multiple R-squared:  0.8846,    Adjusted R-squared:  0.8839 
F-statistic:  1372 on 3 and 537 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Las estimaciones de los coeficientes del modelo sin las obervaciones influyentes han cambiado un poco respecto al modelo original. El <span class="math inline">\(R^2\)</span> ajustado ha incrementado un poco también.</p>
</section>
<section id="lrt-cinta-métrica" class="level3">
<h3 class="anchored" data-anchor-id="lrt-cinta-métrica">LRT cinta métrica</h3>
<p>A continuación se hace una búsqueda del mejor modelo por cada número de posibles combinaciones de variables de las cuales se tenga evidencia que influyen en la talla de adultos mayores, como medida, se usa la medición de la longitud rodilla-talón con cinta métrica. Primero se hará la búsqueda usando todo el conjunto de datos.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Subset selection object
Call: regsubsets.formula(Talla ~ LRT_CM + Edad + Sexo + Etnia, datos, 
    nbest = 1, nvmax = 10)
6 Variables  (and intercept)
                    Forced in Forced out
LRT_CM                  FALSE      FALSE
Edad                    FALSE      FALSE
SexoMasculino           FALSE      FALSE
EtniaBlanco-Mestizo     FALSE      FALSE
EtniaIndigena           FALSE      FALSE
EtniaRrom               FALSE      FALSE
1 subsets of each size up to 6
Selection Algorithm: exhaustive
         LRT_CM Edad SexoMasculino EtniaBlanco-Mestizo EtniaIndigena EtniaRrom
1  ( 1 ) "*"    " "  " "           " "                 " "           " "      
2  ( 1 ) "*"    " "  "*"           " "                 " "           " "      
3  ( 1 ) "*"    "*"  "*"           " "                 " "           " "      
4  ( 1 ) "*"    "*"  "*"           "*"                 " "           " "      
5  ( 1 ) "*"    "*"  "*"           "*"                 "*"           " "      
6  ( 1 ) "*"    "*"  "*"           "*"                 "*"           "*"      </code></pre>
</div>
</div>
<p><span class="math inline">\(R^2\)</span>, <span class="math inline">\(R^2\)</span> ajustado, SCE, y BIC para cada mejor modelo del correspondiente tamaño:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8406283 0.8622339 0.8703559 0.8704753 0.8710482 0.8711093</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8403337 0.8617236 0.8696344 0.8695123 0.8698475 0.8696665</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7765.975 6713.164 6317.387 6311.568 6283.655 6280.677</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  -984.6341 -1057.4421 -1084.1402 -1078.3435 -1074.4531 -1068.4135</code></pre>
</div>
</div>
<p>Usando el criterio BIC, el mejor modelo es el de 3 variables:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelos_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelos_files/figure-html/unnamed-chunk-42-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Los coeficientes del mejor modelo usando el criterio de BIC son:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)        LRT_CM          Edad SexoMasculino 
   57.3048203     2.1612215    -0.1281442     4.1354010 </code></pre>
</div>
</div>
<p>Esto sugiere usar el modelo <span class="math inline">\(Talla = 57.25 + 2.16 LRT\_CM - 0.13 Edad + 4.25 Sexo\)</span>,<br>
<span class="math display">\[Sexo = \begin{cases} 1 &amp; \text{si sexo = hombre} \\ 0 &amp; \text{si sexo = mujer} \end{cases}\]</span></p>
<p>AAhora usamos nuevamente <strong><em>K - fold cross validation</em></strong> con el fin de calcular directamente los errores de predicción sobre los datos de testeo y evitar así el sobreajuste de la misma manera que se realizó para el modelo normal de <span class="math inline">\(LRT_A\)</span>.</p>
<p>El MSE para el modelo de 3 variables (<span class="math inline">\(LRT\_A, Edad, Sexo\)</span>) es:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11.78225</code></pre>
</div>
</div>
<p>Ahora se validarán los supuestos para el mejor modelo obtenido:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Talla ~ LRT_CM + Edad + Sexo, data = datos)

Residuals:
     Min       1Q   Median       3Q      Max 
-10.2270  -2.1500   0.0739   2.1773  10.3679 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   57.30482    3.19489  17.936  &lt; 2e-16 ***
LRT_CM         2.16122    0.05781  37.386  &lt; 2e-16 ***
Edad          -0.12814    0.02205  -5.811 1.06e-08 ***
SexoMasculino  4.13540    0.40019  10.334  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.424 on 539 degrees of freedom
Multiple R-squared:  0.8704,    Adjusted R-squared:  0.8696 
F-statistic:  1206 on 3 and 539 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>El modelo tiene un <span class="math inline">\(R^2\)</span> ajustado de <span class="math inline">\(0.8686\)</span>, es decir que aproximadamente un <span class="math inline">\(86.86\%\)</span> de la variabilidad de la talla es explicada por el modelo.</p>
<p><strong><em>Linealidad:</em></strong> Con el fin de verificar que la relación entre la talla y las variables LRT_CM, Sexo y Edad es lineal, se visualiza el gráfico de los residuos vs los valores predichos del modelo <span class="math inline">\(\left(\hat{y}, \hat{e} \right)\)</span>:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "La media de los residuales es cercana a 0: "</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2.221117e-17</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelos_files/figure-html/unnamed-chunk-47-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El gráfico no muestra ningún patrón marcado, la ubicación de los puntos parece ser aleatoria alrededor de cero, indicando también homoscedasticidad en los residuales y posible independencia de los mismos. El gráfico muestra 3 valores atípicos que valdría la pena explorar.</p>
<p><strong><em>Independencia de los errores:</em></strong> Aunque nuestros datos no son temporales, el test de Durbin-Watson nos puede ayudar a evaluar la autocorrelación de los errores del modelo:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Durbin-Watson test

data:  reg
DW = 2.0982, p-value = 0.8707
alternative hypothesis: true autocorrelation is greater than 0</code></pre>
</div>
</div>
<p>La estadística del test de Durbin-Watson es muy cercano a <span class="math inline">\(2\)</span>, se concluye que los errores son independientes.</p>
<p><strong><em>Normalidad de los errores:</em></strong> Se realiza el gráfico QQ-plot para comparar la distribución de los residuales del modelo con la distribución teórica de una normal. También se hace el test de normalidad de Lilliefors y Anderson-Darling:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelos_files/figure-html/unnamed-chunk-49-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Lilliefors (Kolmogorov-Smirnov) normality test

data:  reg$residuals
D = 0.023514, p-value = 0.66</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Anderson-Darling normality test

data:  reg$residuals
A = 0.35371, p-value = 0.4625</code></pre>
</div>
</div>
<p>El QQ-plot muestra que los residuales se ajustan aceptablemente a una distribución normal. Las pruebas de normalidad de Lilliefors y Anderson-Darling también apoyan este resultado.</p>
<p><strong><em>Homoscedasticidad:</em></strong> Aunque no se vio un patron que indicara heteroscedasticidad en el gráfico de los residuales vs los valores predichos, a continuación se muestra el gráfico de los residuales estandarizados vs los valores predichos con el fin de mejorar la interpretabilidad de la homoscedasticidad y tener una visión más clara de las observaciones atípicas e influyentes:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelos_files/figure-html/unnamed-chunk-50-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>No se observan patrones que indiquen hereroscedasticidad en los residuos (forma de cono o embudo). Se siguien observando algunas observaciones atípicas y/o influyentes.</p>
<p>Adicional, se realiza la prueba de Breusch-Pagan para verificar la homoscedasticidad de los residuales:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    studentized Breusch-Pagan test

data:  reg
BP = 4.524, df = 3, p-value = 0.2102</code></pre>
</div>
</div>
<p>No se rechaza la hipótesis nula de que los errores del modelo son homoscedasticos.</p>
<p><strong><em>Multicolinealidad:</em></strong> Se verifica que las variables incluídas en el modelo no están altamente correlacionadas entre sí, y así evitar obtener resultados inestables que dificulten la interpretabilidad de los coeficientes del modelo. Se calculan los Factores de Inflación de la Varianza (VIFs):</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  LRT_CM     Edad     Sexo 
1.805247 1.037625 1.854874 </code></pre>
</div>
</div>
<p>Dado que los VIFs son mucho menores a 5, esto indica que cada variable tiene una correlación moderada (leve) con las demás. Por lo que se puede concluir que los resultados del modelo posiblemente no estarán muy afectados por la multicolinealidad.</p>
<p><strong><em>El modelo está bien especificado:</em></strong> Se hace el test de RESET para examinar si el modelo ajustado está bien especificado o si se han omitido términos no lineales o interacciones importantes:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    RESET test

data:  reg
RESET = 0.95259, df1 = 4, df2 = 535, p-value = 0.4332</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    RESET test

data:  reg
RESET = 0.52406, df1 = 2, df2 = 537, p-value = 0.5924</code></pre>
</div>
</div>
<p>No se rechaza la hipótesis nula de que el modelo está bien especificado.</p>
<p><strong><em>Observaciones atípicas y de alto apalancamiento:</em></strong></p>
<div>

</div>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="modelos_files/figure-html/unnamed-chunk-54-1.png" class="img-fluid" width="672"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="modelos_files/figure-html/unnamed-chunk-54-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
<p>Usando los residuales estudentizados, se observan <span class="math inline">\(5\)</span> datos atípicos.</p>
<div>

</div>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="modelos_files/figure-html/unnamed-chunk-55-1.png" class="img-fluid" width="672"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="modelos_files/figure-html/unnamed-chunk-55-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="quarto-layout-row">
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>       StudRes         Hat       CookD
41  -3.0080070 0.016908956 0.038333988
346 -3.0192135 0.006311404 0.014259783
363  3.0588792 0.004620190 0.010691877
505 -0.7271639 0.030472832 0.004158506
520 -2.7728983 0.012919280 0.024850615
538 -0.5481181 0.027348700 0.002114618</code></pre>
</div>
</div>
</div>
<p>En total 29 observaciones superan el umbral especificado para la distancia de Cook, pero esto no significa que todas sean influyentes (alto apalancamiento). Particularmente hay <span class="math inline">\(3\)</span> observaciones que son marcadas como influyentes significativamente según la distancia de Cook (43, 504 y 533) . Esto indica que la inclusión de estas observaciones en el modelo pueden tener una influencia significativa en los coeficientes del modelo y en la predicción de la talla. Se debe explorar con cautela estas observaciones y decidir qué hacer con ellas.</p>
<p>Para esto, se puede comprobar el cambio en los coeficientes del modelo al excluir estas observaciones influyentes.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Talla ~ LRT_CM + Edad + Sexo, data = datos, subset = {
    setdiff(row(datos)[, 1], c(533, 43, 504))
})

Residuals:
    Min      1Q  Median      3Q     Max 
-10.232  -2.158   0.065   2.165  10.364 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   57.44618    3.20775  17.909  &lt; 2e-16 ***
LRT_CM         2.15628    0.05825  37.017  &lt; 2e-16 ***
Edad          -0.12667    0.02215  -5.718  1.8e-08 ***
SexoMasculino  4.14110    0.40059  10.338  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.426 on 536 degrees of freedom
Multiple R-squared:  0.8684,    Adjusted R-squared:  0.8676 
F-statistic:  1179 on 3 and 536 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Las estimaciones de los coeficientes del modelo sin las obervaciones influyentes han cambiado un poco respecto al modelo original. El <span class="math inline">\(R^2\)</span> ajustado ha incrementado un poco también.</p>
</section>
<section id="lrm-pierna-estirada" class="level3">
<h3 class="anchored" data-anchor-id="lrm-pierna-estirada">LRM pierna estirada</h3>
<p>A continuación se hace una búsqueda del mejor modelo por cada número de posibles combinaciones de variables de las cuales se tenga evidencia que influyen en la talla de adultos mayores, solo se tiene en cuenta la medición de la longitud rodilla-maléolo con la pierna estirada. Primero se hará la búsqueda usando todo el conjunto de datos.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Subset selection object
Call: regsubsets.formula(Talla ~ LRM_R + Edad + Sexo + Etnia, datos, 
    nbest = 1, nvmax = 10)
6 Variables  (and intercept)
                    Forced in Forced out
LRM_R                   FALSE      FALSE
Edad                    FALSE      FALSE
SexoMasculino           FALSE      FALSE
EtniaBlanco-Mestizo     FALSE      FALSE
EtniaIndigena           FALSE      FALSE
EtniaRrom               FALSE      FALSE
1 subsets of each size up to 6
Selection Algorithm: exhaustive
         LRM_R Edad SexoMasculino EtniaBlanco-Mestizo EtniaIndigena EtniaRrom
1  ( 1 ) "*"   " "  " "           " "                 " "           " "      
2  ( 1 ) "*"   " "  "*"           " "                 " "           " "      
3  ( 1 ) "*"   "*"  "*"           " "                 " "           " "      
4  ( 1 ) "*"   "*"  "*"           " "                 " "           "*"      
5  ( 1 ) "*"   "*"  "*"           "*"                 "*"           " "      
6  ( 1 ) "*"   "*"  "*"           "*"                 "*"           "*"      </code></pre>
</div>
</div>
<p><span class="math inline">\(R^2\)</span>, <span class="math inline">\(R^2\)</span> ajustado, SCE, y BIC para cada mejor modelo del correspondiente tamaño:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8341945 0.8516241 0.8581963 0.8583950 0.8588665 0.8595238</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8338880 0.8510745 0.8574070 0.8573422 0.8575524 0.8579513</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8079.489 7230.166 6909.911 6900.229 6877.253 6845.224</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  -963.144 -1017.156 -1035.460 -1029.924 -1025.438 -1021.676</code></pre>
</div>
</div>
<p>Usando el criterio BIC, el mejor modelo es el de 3 variables:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelos_files/figure-html/unnamed-chunk-59-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelos_files/figure-html/unnamed-chunk-59-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Los coeficientes del mejor modelo usando el criterio de BIC son:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)         LRM_R          Edad SexoMasculino 
    68.048537      2.217070     -0.115388      3.814406 </code></pre>
</div>
</div>
<p>Nuevamente se hará la búsqueda del mejor modelo usando <strong><em>K - fold cross validation</em></strong> con el fin de calcular directamente los errores de predicción sobre los datos de testeo y evitar así el sobreajuste.</p>
<p>El MSE para el modelo de 3 variables (<span class="math inline">\(LRT\_A, Edad, Sexo\)</span>) es:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12.99465</code></pre>
</div>
</div>
<p>Ahora se validarán los supuestos para el mejor modelo obtenido:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Talla ~ LRM_R + Edad + Sexo, data = datos)

Residuals:
     Min       1Q   Median       3Q      Max 
-13.1766  -2.1806   0.0388   2.2805  10.1682 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   68.04854    3.12423  21.781  &lt; 2e-16 ***
LRM_R          2.21707    0.06317  35.095  &lt; 2e-16 ***
Edad          -0.11539    0.02309  -4.998 7.84e-07 ***
SexoMasculino  3.81441    0.42819   8.908  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.58 on 539 degrees of freedom
Multiple R-squared:  0.8582,    Adjusted R-squared:  0.8574 
F-statistic:  1087 on 3 and 539 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>El modelo propuesto parala medida Longitud Rodilla-Maleólo <span class="math inline">\((LRM_R)\)</span> con la pierna estirada es:</p>
<p><span class="math display">\[Talla = 68.83 + 2.21 \, LRM_R - 0.12 \, Edad+ 3.87 \, Sexo \]</span></p>
<p>Según el <span class="math inline">\(R^2\)</span> ajustado aproximadamente un <span class="math inline">\(85.81\%\)</span> de la variabilidad de la talla es explicada por el modelo.</p>
<p><strong><em>Linealidad:</em></strong> Con el fin de verificar que la relación entre la talla y las variables LRM_R (discriminando por sexo) y la edad es lineal, se visualiza el gráfico de los residuos vs los valores predichos del modelo <span class="math inline">\(\left(\hat{e},\hat{y} \right)\)</span>:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelos_files/figure-html/unnamed-chunk-64-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El gráfico no muestra ningún patrón marcado, la ubicación de los puntos parece ser aleatoria alrededor de cero, indicando también homoscedasticidad en los residuales y posible independencia de los mismos. El gráfico muestra algunos valores atípicos que valdría la pena explorar.</p>
<p><strong><em>Independencia de los errores:</em></strong> Aunque nuestros datos no son temporales, el test de Durbin-Watson nos puede ayudar a evaluar la autocorrelación de los errores del modelo:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Durbin-Watson test

data:  reg
DW = 1.907, p-value = 0.2713
alternative hypothesis: true autocorrelation is not 0</code></pre>
</div>
</div>
<p>La estadística del test de Durbin-Watson es muy cercano a <span class="math inline">\(2\)</span>, se concluye que los errores son independientes.</p>
<p><strong><em>Normalidad de los errores:</em></strong> Se realiza el gráfico QQ-plot para comparar la distribución de los residuales del modelo con la distribución teórica de una normal. También se hace el test de normalidad de Lilliefors y Anderson-Darling:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelos_files/figure-html/unnamed-chunk-66-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Lilliefors (Kolmogorov-Smirnov) normality test

data:  reg$residuals
D = 0.021779, p-value = 0.7687</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Anderson-Darling normality test

data:  reg$residuals
A = 0.30194, p-value = 0.5759</code></pre>
</div>
</div>
<p>El QQ-plot muestra que los residuales se ajustan aceptablemente a una distribución normal. Las pruebas de normalidad de Lilliefors y Anderson-Darling también apoyan este resultado.</p>
<p><strong><em>Homoscedasticidad:</em></strong> Aunque no se vio un patron que indicara heteroscedasticidad en el gráfico de los residuales vs los valores predichos, a continuación se muestra el gráfico de los residuales estandarizados vs los valores predichos con el fin de mejorar la interpretabilidad de la homoscedasticidad y tener una visión más clara de las observaciones atípicas e influyentes:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelos_files/figure-html/unnamed-chunk-67-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>No se observan patrones que indiquen hereroscedasticidad en los residuos (forma de cono o embudo). Se siguien observando algunas observaciones atípicas y/o influyentes.</p>
<p>Adicional, se realiza la prueba de Breusch-Pagan para verificar la homoscedasticidad de los residuales:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Breusch-Pagan test

data:  reg
BP = 7.9093, df = 3, p-value = 0.04792</code></pre>
</div>
</div>
<p>Se rechaza la hipótesis nula de que los errores del modelo son homoscedasticos.</p>
<p><strong><em>Multicolinealidad:</em></strong> Se verifica que las variables incluídas en el modelo no están altamente correlacionadas entre sí, y así evitar obtener resultados inestables que dificulten la interpretabilidad de los coeficientes del modelo. Se calculan los Factores de Inflación de la Varianza (VIFs):</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   LRM_R     Edad     Sexo 
1.887057 1.039726 1.941441 </code></pre>
</div>
</div>
<p>Dado que los VIFs son mucho menores a 5, cada variable tiene una correlación moderada (leve) con las demás. Los resultados del modelo no deberían verse afectados por la multicolinealidad.</p>
<p><strong><em>El modelo está bien especificado:</em></strong> Se hace el test de RESET para examinar si el modelo ajustado está bien especificado o si se han omitido términos no lineales o interacciones importantes:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    RESET test

data:  reg
RESET = 0.73773, df1 = 4, df2 = 535, p-value = 0.5665</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    RESET test

data:  reg
RESET = 0.045213, df1 = 2, df2 = 537, p-value = 0.9558</code></pre>
</div>
</div>
<p>No se rechaza la hipótesis nula de que el modelo está bien especificado.</p>
<p><strong><em>Observaciones atípicas y de alto apalancamiento:</em></strong></p>
<div>

</div>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="modelos_files/figure-html/unnamed-chunk-71-1.png" class="img-fluid" width="672"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="modelos_files/figure-html/unnamed-chunk-71-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
<p>Usando los residuales estudentizados, se observan <span class="math inline">\(5\)</span> datos atípicos.</p>
<div>

</div>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="modelos_files/figure-html/unnamed-chunk-72-1.png" class="img-fluid" width="672"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="modelos_files/figure-html/unnamed-chunk-72-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="quarto-layout-row">
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>       StudRes         Hat        CookD
505  0.1915271 0.033494744 0.0003183829
520 -3.7396744 0.008271635 0.0284752514
529 -3.4640045 0.009155150 0.0271633483
538 -0.2905027 0.030237545 0.0006589612</code></pre>
</div>
</div>
</div>
<p>En total 29 observaciones superan el umbral especificado para la distancia de Cook, pero esto no significa que todas sean influyentes (alto apalancamiento). Particularmente hay 3 observaciones que son marcadas como influyentes significativamente según la distancia de Cook (504, 533, 542). Esto indica que la inclusión de estas observaciones en el modelo pueden tener una influencia significativa en los coeficientes del modelo y en la predicción de la talla. Se debe explorar con cautela estas observaciones y decidir qué hacer con ellas.</p>
<p>Para esto, se puede comprobar el cambio en los coeficientes del modelo al excluir estas observaciones influyentes.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Talla ~ LRM_R + Edad + Sexo, data = datos, subset = {
    setdiff(row(datos)[, 1], c(533, 542, 504))
})

Residuals:
    Min      1Q  Median      3Q     Max 
-13.226  -2.208   0.027   2.274  10.186 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   68.82332    3.12440  22.028  &lt; 2e-16 ***
LRM_R          2.20499    0.06321  34.884  &lt; 2e-16 ***
Edad          -0.11872    0.02306  -5.148  3.7e-07 ***
SexoMasculino  3.82495    0.42647   8.969  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.564 on 536 degrees of freedom
Multiple R-squared:  0.8574,    Adjusted R-squared:  0.8566 
F-statistic:  1074 on 3 and 536 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Las estimaciones de los coeficientes del modelo sin las obervaciones influyentes han cambiado un poco respecto al modelo original. El <span class="math inline">\(R^2\)</span> ajustado ha incrementado un poco también.</p>
</section>
<section id="lrm-pierna-a-90" class="level3">
<h3 class="anchored" data-anchor-id="lrm-pierna-a-90">LRM pierna a 90°</h3>
<p>Ahora, se hará una búsqueda del mejor modelo por cada número de posibles combinaciones de variables de las cuales se tenga evidencia que influyen en la talla de adultos mayores, únicamente se tiene en cuenta la longitud rodilla-malélo con la pierna a 90°. Primero se hará la búsqueda usando todo el conjunto de datos.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Subset selection object
Call: regsubsets.formula(Talla ~ LRM_90 + Edad + Sexo + Etnia, datos, 
    nbest = 1, nvmax = 10)
6 Variables  (and intercept)
                    Forced in Forced out
LRM_90                  FALSE      FALSE
Edad                    FALSE      FALSE
SexoMasculino           FALSE      FALSE
EtniaBlanco-Mestizo     FALSE      FALSE
EtniaIndigena           FALSE      FALSE
EtniaRrom               FALSE      FALSE
1 subsets of each size up to 6
Selection Algorithm: exhaustive
         LRM_90 Edad SexoMasculino EtniaBlanco-Mestizo EtniaIndigena EtniaRrom
1  ( 1 ) "*"    " "  " "           " "                 " "           " "      
2  ( 1 ) "*"    " "  "*"           " "                 " "           " "      
3  ( 1 ) "*"    "*"  "*"           " "                 " "           " "      
4  ( 1 ) "*"    "*"  "*"           "*"                 " "           " "      
5  ( 1 ) "*"    "*"  "*"           "*"                 " "           "*"      
6  ( 1 ) "*"    "*"  "*"           "*"                 "*"           "*"      </code></pre>
</div>
</div>
<p><span class="math inline">\(R^2\)</span>, <span class="math inline">\(R^2\)</span> ajustado, SCE, y BIC para cada mejor modelo del correspondiente tamaño:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8177673 0.8498836 0.8568161 0.8569974 0.8571902 0.8574563</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8174305 0.8493276 0.8560191 0.8559342 0.8558605 0.8558607</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8879.962 7314.976 6977.167 6968.333 6958.938 6945.970</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  -911.8475 -1010.8238 -1030.2001 -1024.5910 -1019.0264 -1013.7421</code></pre>
</div>
</div>
<p>Usando el criterio BIC, el mejor modelo es el de 3 variables:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelos_files/figure-html/unnamed-chunk-76-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelos_files/figure-html/unnamed-chunk-76-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Los coeficientes del mejor modelo usando el criterio de BIC son:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)        LRM_90          Edad SexoMasculino 
   66.2016693     2.2163573    -0.1184789     4.8293028 </code></pre>
</div>
</div>
<p>Esto sugiere usar el modelo <span class="math inline">\(Talla = 69.33 + 2.12 LRM\_90 - 0.11 Edad + 5.18 Sexo\)</span>,<br>
<span class="math display">\[Sexo = \begin{cases} 1 &amp; \text{si sexo = hombre} \\ 0 &amp; \text{si sexo = mujer} \end{cases}\]</span></p>
<p>Ahora se hará la búsqueda del mejor modelo usando <strong><em>K - fold cross validation</em></strong> con el fin de calcular directamente los errores de predicción sobre los datos de testeo y evitar así el sobreajuste.</p>
<p>El MSE para el modelo de 3 variables (<span class="math inline">\(LRT\_A, Edad, Sexo\)</span>) es:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 13.08059</code></pre>
</div>
</div>
<p>Ahora se validarán los supuestos para el mejor modelo obtenido:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Talla ~ LRM_90 + Edad + Sexo, data = datos)

Residuals:
     Min       1Q   Median       3Q      Max 
-12.6469  -2.3083   0.0517   2.3260   9.4260 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   66.20167    3.18952  20.756  &lt; 2e-16 ***
LRM_90         2.21636    0.06360  34.851  &lt; 2e-16 ***
Edad          -0.11848    0.02319  -5.108 4.51e-07 ***
SexoMasculino  4.82930    0.41132  11.741  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.598 on 539 degrees of freedom
Multiple R-squared:  0.8568,    Adjusted R-squared:  0.856 
F-statistic:  1075 on 3 and 539 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>El <span class="math inline">\(R^2\)</span> ajustado indica que aproximadamente un <span class="math inline">\(83.89\%\)</span> de la variabilidad de la talla es explicada por LRT_CM, la edad y el sexo.</p>
<p><strong><em>Linealidad:</em></strong> Con el fin de verificar que la relación entre la talla y las variables LRT_CM (discriminando por sexo) y la edad es lineal, se visualiza el gráfico de los residuos vs los valores predichos del modelo <span class="math inline">\(\left(\hat{e},\hat{y} \right)\)</span>:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelos_files/figure-html/unnamed-chunk-81-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El gráfico no muestra ningún patrón marcado, la ubicación de los puntos parece ser aleatoria alrededor de cero, indicando también homoscedasticidad en los residuales y posible independencia de los mismos. El gráfico muestra algunos valores atípicos que valdría la pena explorar.</p>
<p><strong><em>Independencia de los errores:</em></strong> Aunque nuestros datos no son temporales, el test de Durbin-Watson nos puede ayudar a evaluar la autocorrelación de los errores del modelo:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Durbin-Watson test

data:  reg
DW = 2.0296, p-value = 0.7428
alternative hypothesis: true autocorrelation is not 0</code></pre>
</div>
</div>
<p>La estadística del test de Durbin-Watson es muy cercano a <span class="math inline">\(2\)</span>, se concluye que los errores son independientes.</p>
<p><strong><em>Normalidad de los errores:</em></strong> Se realiza el gráfico QQ-plot para comparar la distribución de los residuales del modelo con la distribución teórica de una normal. También se hace el test de normalidad de Lilliefors y Anderson-Darling:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelos_files/figure-html/unnamed-chunk-83-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Lilliefors (Kolmogorov-Smirnov) normality test

data:  reg$residuals
D = 0.019781, p-value = 0.8725</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Anderson-Darling normality test

data:  reg$residuals
A = 0.20655, p-value = 0.8687</code></pre>
</div>
</div>
<p>El QQ-plot muestra que los residuales se ajustan aceptablemente a una distribución normal. Las pruebas de normalidad de Lilliefors y Anderson-Darling también apoyan este resultado.</p>
<p><strong><em>Homoscedasticidad:</em></strong> Aunque no se vio un patron que indicara heteroscedasticidad en el gráfico de los residuales vs los valores predichos, a continuación se muestra el gráfico de los residuales estandarizados vs los valores predichos con el fin de mejorar la interpretabilidad de la homoscedasticidad y tener una visión más clara de las observaciones atípicas e influyentes:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelos_files/figure-html/unnamed-chunk-84-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>No se observan patrones que indiquen hereroscedasticidad en los residuos (forma de cono o embudo). Se siguien observando algunas observaciones atípicas y/o influyentes.</p>
<p>Adicional, se realiza la prueba de Breusch-Pagan para verificar la homoscedasticidad de los residuales:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    studentized Breusch-Pagan test

data:  reg
BP = 6.2678, df = 3, p-value = 0.09928</code></pre>
</div>
</div>
<p>No se rechaza la hipótesis nula de que los errores del modelo son homoscedasticos.</p>
<p><strong><em>Multicolinealidad:</em></strong> Se verifica que las variables incluídas en el modelo no están altamente correlacionadas entre sí, y así evitar obtener resultados inestables que dificulten la interpretabilidad de los coeficientes del modelo. Se calculan los Factores de Inflación de la Varianza (VIFs):</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  LRM_90     Edad     Sexo 
1.722901 1.039214 1.774241 </code></pre>
</div>
</div>
<p>Dado que los VIFs son mucho menores a 5, esto indica que cada variable tiene una correlación moderada (leve) con las demás. Por lo que se puede concluir que los resultados del modelo posiblemente no estarán muy afectados por la multicolinealidad.</p>
<p><strong><em>El modelo está bien especificado:</em></strong> Se hace el test de RESET para examinar si el modelo ajustado está bien especificado o si se han omitido términos no lineales o interacciones importantes:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    RESET test

data:  reg
RESET = 0.58122, df1 = 4, df2 = 535, p-value = 0.6764</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    RESET test

data:  reg
RESET = 0.060873, df1 = 2, df2 = 537, p-value = 0.9409</code></pre>
</div>
</div>
<p>En ambos casos, se rechaza la hipótesis nula de que el modelo está bien especificado.</p>
<p><strong><em>Observaciones atípicas y de alto apalancamiento:</em></strong></p>
<div>

</div>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="modelos_files/figure-html/unnamed-chunk-88-1.png" class="img-fluid" width="672"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="modelos_files/figure-html/unnamed-chunk-88-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
<p>Usando los residuales estudentizados, se observan <span class="math inline">\(5\)</span> datos atípicos.</p>
<div>

</div>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="modelos_files/figure-html/unnamed-chunk-89-1.png" class="img-fluid" width="672"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="modelos_files/figure-html/unnamed-chunk-89-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="quarto-layout-row">
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>        StudRes         Hat        CookD
319  2.11601917 0.020793022 2.361725e-02
505 -0.79314248 0.030301485 4.917774e-03
520 -3.56904969 0.008879093 2.792099e-02
529 -3.15390454 0.009360814 2.311454e-02
538  0.04476221 0.033442829 1.736374e-05</code></pre>
</div>
</div>
</div>
<p>En total 29 observaciones superan el umbral especificado para la distancia de Cook, pero esto no significa que todas sean influyentes (alto leverage). Particularmente hay 3 observaciones que son marcadas como influyentes significativamente según la distancia de Cook (80, 147 y 533). Esto indica que la inclusión de estas observaciones en el modelo pueden tener una influencia significativa en los coeficientes del modelo y en la predicción de la talla. Se debe explorar con cautela estas observaciones y decidir qué hacer con ellas.</p>
<p>Para esto, se puede comprobar el cambio en los coeficientes del modelo al excluir estas observaciones influyentes.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Talla ~ LRM_90 + Edad + Sexo, data = datos, subset = {
    setdiff(row(datos)[, 1], c(80, 147, 533))
})

Residuals:
     Min       1Q   Median       3Q      Max 
-12.6630  -2.3161   0.0703   2.3319   9.3897 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   66.21875    3.19376  20.734  &lt; 2e-16 ***
LRM_90         2.21167    0.06381  34.660  &lt; 2e-16 ***
Edad          -0.11590    0.02321  -4.993 8.04e-07 ***
SexoMasculino  4.83615    0.41177  11.745  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.594 on 536 degrees of freedom
Multiple R-squared:  0.8563,    Adjusted R-squared:  0.8555 
F-statistic:  1065 on 3 and 536 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Las estimaciones de los coeficientes del modelo sin las obervaciones influyentes han cambiado un poco respecto al modelo original. El <span class="math inline">\(R^2\)</span> ajustado ha incrementado un poco también.</p>
</section>
<section id="resúmen-de-los-modelos-normales." class="level3">
<h3 class="anchored" data-anchor-id="resúmen-de-los-modelos-normales.">Resúmen de los modelos normales.</h3>
<p>Todos los modelos usaron las variables Edad, Sexo y el intercepto variando entre LRT_A, LRT_CM, LRM_90 y LRM_R. Todos obtuvieron un coeficientes diferentes.</p>
<p>La tabla de los errores cuadráticos medios para la regresión lineal simple es la siguiente:</p>
<div class="cell">
<div class="cell-output-display">
<div id="wgmtnpgdml" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>@import url("https://fonts.googleapis.com/css2?family=Chivo:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap");
@import url("https://fonts.googleapis.com/css2?family=Chivo:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap");
@import url("https://fonts.googleapis.com/css2?family=Chivo:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap");
@import url("https://fonts.googleapis.com/css2?family=Cairo:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap");
#wgmtnpgdml table {
  font-family: Cairo, system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#wgmtnpgdml thead, #wgmtnpgdml tbody, #wgmtnpgdml tfoot, #wgmtnpgdml tr, #wgmtnpgdml td, #wgmtnpgdml th {
  border-style: none;
}

#wgmtnpgdml p {
  margin: 0;
  padding: 0;
}

#wgmtnpgdml .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 9px;
  font-weight: 400;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: none;
  border-top-width: 3px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#wgmtnpgdml .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#wgmtnpgdml .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#wgmtnpgdml .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#wgmtnpgdml .gt_heading {
  background-color: #FFFFFF;
  text-align: left;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#wgmtnpgdml .gt_bottom_border {
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#wgmtnpgdml .gt_col_headings {
  border-top-style: none;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #000000;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#wgmtnpgdml .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#wgmtnpgdml .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#wgmtnpgdml .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#wgmtnpgdml .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#wgmtnpgdml .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #000000;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#wgmtnpgdml .gt_spanner_row {
  border-bottom-style: hidden;
}

#wgmtnpgdml .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: none;
  border-top-width: 2px;
  border-top-color: #000000;
  border-bottom-style: solid;
  border-bottom-width: 1px;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#wgmtnpgdml .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: none;
  border-top-width: 2px;
  border-top-color: #000000;
  border-bottom-style: solid;
  border-bottom-width: 1px;
  border-bottom-color: #FFFFFF;
  vertical-align: middle;
}

#wgmtnpgdml .gt_from_md > :first-child {
  margin-top: 0;
}

#wgmtnpgdml .gt_from_md > :last-child {
  margin-bottom: 0;
}

#wgmtnpgdml .gt_row {
  padding-top: 3px;
  padding-bottom: 3px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#wgmtnpgdml .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 0px;
  border-right-color: #FFFFFF;
  padding-left: 5px;
  padding-right: 5px;
}

#wgmtnpgdml .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#wgmtnpgdml .gt_row_group_first td {
  border-top-width: 2px;
}

#wgmtnpgdml .gt_row_group_first th {
  border-top-width: 2px;
}

#wgmtnpgdml .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#wgmtnpgdml .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#wgmtnpgdml .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#wgmtnpgdml .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#wgmtnpgdml .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#wgmtnpgdml .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#wgmtnpgdml .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#wgmtnpgdml .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#wgmtnpgdml .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#wgmtnpgdml .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#wgmtnpgdml .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#wgmtnpgdml .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#wgmtnpgdml .gt_sourcenote {
  font-size: 12px;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#wgmtnpgdml .gt_left {
  text-align: left;
}

#wgmtnpgdml .gt_center {
  text-align: center;
}

#wgmtnpgdml .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#wgmtnpgdml .gt_font_normal {
  font-weight: normal;
}

#wgmtnpgdml .gt_font_bold {
  font-weight: bold;
}

#wgmtnpgdml .gt_font_italic {
  font-style: italic;
}

#wgmtnpgdml .gt_super {
  font-size: 65%;
}

#wgmtnpgdml .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#wgmtnpgdml .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#wgmtnpgdml .gt_indent_1 {
  text-indent: 5px;
}

#wgmtnpgdml .gt_indent_2 {
  text-indent: 10px;
}

#wgmtnpgdml .gt_indent_3 {
  text-indent: 15px;
}

#wgmtnpgdml .gt_indent_4 {
  text-indent: 20px;
}

#wgmtnpgdml .gt_indent_5 {
  text-indent: 25px;
}

#wgmtnpgdml .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#wgmtnpgdml div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}

tbody tr:last-child {
  border-bottom: 2px solid #ffffff00;
}
</style>

<table class="gt_table caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="header gt_col_headings">
<th id="Modelo" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" style="border-top-width: 0px; border-top-style: solid; border-top-color: black; font-family: Chivo; font-size: 14px; vertical-align: bottom; font-weight: 200; text-transform: uppercase" scope="col">Modelo</th>
<th id="Medida" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" style="border-top-width: 0px; border-top-style: solid; border-top-color: black; font-family: Chivo; font-size: 14px; vertical-align: bottom; font-weight: 200; text-transform: uppercase" scope="col">Medida</th>
<th id="MSE" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" style="border-top-width: 0px; border-top-style: solid; border-top-color: black; font-family: Chivo; font-size: 14px; vertical-align: bottom; font-weight: 200; text-transform: uppercase" scope="col">MSE</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="Modelo">Normal</td>
<td class="gt_row gt_left" headers="Medida">LRT_A</td>
<td class="gt_row gt_right" headers="MSE">10.39225</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Modelo">Normal</td>
<td class="gt_row gt_left" headers="Medida">LRT_CM</td>
<td class="gt_row gt_right" headers="MSE">11.78225</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Modelo">Normal</td>
<td class="gt_row gt_left" headers="Medida">LRM_R</td>
<td class="gt_row gt_right" headers="MSE">12.99465</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>El modelo que mejor comportamiento tuvo fue: <span class="math inline">\(Talla = 58.67 + 2.19 LRT\_A - 0.12Edad + 3.06Sexo\)</span></p>
<p>Sin embargo, vemos que también se tuvieron buenos resultados con</p>
<p><span class="math inline">\(Talla = 57.25 + 2.16 LRT\_CM - 0.13 Edad + 4.25 \, Sexo\)</span>,<br>
</p>
<p>donde</p>
<p><span class="math display">\[Sexo = \begin{cases} 1 &amp; \text{si sexo = hombre} \\ 0 &amp; \text{si sexo = mujer} \end{cases}\]</span></p>
<p>Se validó que estos dos modelos en particular cumplen con los supuestos. \</p>
<p>Aúnque estos tienen cada uno 3 observaciones con alto apalancamiento, el cambio al reajustar sin estas no parece ser muy grande.</p>
</section>
</section>
<section id="modelo-lasso" class="level2">
<h2 class="anchored" data-anchor-id="modelo-lasso">Modelo Lasso</h2>
<p>En este modelo se incluirán las cuatro mediciones, con el fin de escoger la mejor. Se espera que el modelo sea capaz de inducir escasez en los coeficientes del modelo, especialmente a los correspondientes a las mediciones LRT_A, LRT_CM, LRM_90 y LRM_R, de tal manera que pueda escoger la medición que al momento de estimar la talla sea más precisa.</p>
<p>Se particionan los datos en entrenamiento y prueba,</p>
<p>Algunos coeficientes se hacen cero:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelos_files/figure-html/unnamed-chunk-93-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Se hace <strong><em>k-fold cross validation</em></strong> con <span class="math inline">\(k = 10\)</span> y se promedia el MSE:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelos_files/figure-html/unnamed-chunk-94-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11.5243</code></pre>
</div>
</div>
<p>Los coeficientes del modelo resultante son:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                 (Intercept)                        LRT_A 
                 57.29164584                   1.47139307 
                      LRT_CM                       LRM_90 
                  0.33657697                   0.00000000 
                       LRM_R                         Edad 
                  0.39443067                  -0.09754163 
                        Peso                SexoMasculino 
                  0.01611356                   2.94003896 
         EtniaBlanco-Mestizo                EtniaIndigena 
                  0.00000000                   0.14135913 
                   EtniaRrom ProgramaComunidad de Cuidado 
                  0.00000000                   0.00000000 </code></pre>
</div>
</div>
<p>y los coeficientes distintos de cero:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)         LRT_A        LRT_CM         LRM_R          Edad 
  57.29164584    1.47139307    0.33657697    0.39443067   -0.09754163 
         Peso SexoMasculino EtniaIndigena 
   0.01611356    2.94003896    0.14135913 </code></pre>
</div>
</div>
<p>Se observa que algunos coeficientes se hicieron cero, incluyendo el de LRM_90. Pero aún así el modelo todavía incluye LRT_A, LRT_CM y LRM_R al tiempo. Esto puede ser debido a que cada una de las mediciones está muy correlacionada con la talla y que además están muy correlacionadas entre ellas. Se observa que LRT_A tiene un coeficiente mucho mayor que LRT_CM y LRM_R haciendo ver que el modelo las trató de llevar a cero pero no por completo.</p>
<p>El MSE de este modelo sobre los datos de prueba fue de <span class="math inline">\(8.92\)</span>. Se puede probar aumentar el valor de <span class="math inline">\(\lambda\)</span> (sumando pequeñas cantidades al <span class="math inline">\(\lambda\)</span> que minimizó el MSE en la validación cruzada), resultará un modelo más sencillo a la vez que aumenta el MSE sobre los datos de prueba.</p>
</section>
<section id="lasso-sin-tener-en-cuenta-lrt_a" class="level2">
<h2 class="anchored" data-anchor-id="lasso-sin-tener-en-cuenta-lrt_a">Lasso sin tener en cuenta LRT_A</h2>
<p>Ya que la idea es estimar la altura de los adultos mayores usando alguno de los métodos más sencillos y accecibles para quienes toman las medidas, se excluye en este modelo LRT_A ya que es de difícil acceso y poco económico.</p>
<p>Se ajusta el modelo Lasso con las tres mediciones LRT_CM, LRM_90 y LRM_R.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelos_files/figure-html/unnamed-chunk-97-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11.76477</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                 (Intercept)                       LRT_CM 
                 55.67448255                   1.22970856 
                      LRM_90                        LRM_R 
                 -0.04521568                   1.02615376 
                        Edad                         Peso 
                 -0.11163896                   0.03635586 
               SexoMasculino          EtniaBlanco-Mestizo 
                  3.58099321                   2.23789428 
               EtniaIndigena                    EtniaRrom 
                  3.26643048                   2.74464572 
ProgramaComunidad de Cuidado 
                  0.34506102 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                 (Intercept)                       LRT_CM 
                 55.67448255                   1.22970856 
                      LRM_90                        LRM_R 
                 -0.04521568                   1.02615376 
                        Edad                         Peso 
                 -0.11163896                   0.03635586 
               SexoMasculino          EtniaBlanco-Mestizo 
                  3.58099321                   2.23789428 
               EtniaIndigena                    EtniaRrom 
                  3.26643048                   2.74464572 
ProgramaComunidad de Cuidado 
                  0.34506102 </code></pre>
</div>
</div>
<p>El modelo sugiere incluir al tiempo LRT_CM y LRM_R. Para este modelo el MSE sobre el conjunto de test fue de <span class="math inline">\(10.30\)</span>.</p>
<p>Se ajusta el valor de <span class="math inline">\(\lambda\)</span> con el fin de llevar a cero algunos coeficientes adicionales:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11.66938</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                 (Intercept)                       LRT_CM 
                 57.38062215                   1.23449408 
                      LRM_90                        LRM_R 
                  0.00000000                   0.96809366 
                        Edad                         Peso 
                 -0.09233139                   0.02968841 
               SexoMasculino          EtniaBlanco-Mestizo 
                  3.43405025                   0.00000000 
               EtniaIndigena                    EtniaRrom 
                  0.07658140                   0.00000000 
ProgramaComunidad de Cuidado 
                  0.04219502 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                 (Intercept)                       LRT_CM 
                 57.38062215                   1.23449408 
                       LRM_R                         Edad 
                  0.96809366                  -0.09233139 
                        Peso                SexoMasculino 
                  0.02968841                   3.43405025 
               EtniaIndigena ProgramaComunidad de Cuidado 
                  0.07658140                   0.04219502 </code></pre>
</div>
</div>
<p>Se obtiene un modelo más sencillo con un MSE de <span class="math inline">\(10.37\)</span>.</p>
</section>
<section id="modelo-lasso-1" class="level2">
<h2 class="anchored" data-anchor-id="modelo-lasso-1">Modelo Lasso</h2>
<section id="lrt-antropómetro-1" class="level3">
<h3 class="anchored" data-anchor-id="lrt-antropómetro-1">LRT Antropómetro</h3>
<p>Se particionan los datos en entrenamiento y prueba,</p>
<p>Algunos coeficientes se hacen cero:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelos_files/figure-html/unnamed-chunk-100-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Se hace <strong><em>k-fold cross validation</em></strong> con <span class="math inline">\(k = 10\)</span> y se promedia el MSE:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelos_files/figure-html/unnamed-chunk-101-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11.73922</code></pre>
</div>
</div>
<p>Los coeficientes del modelo resultante son:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>        (Intercept)               LRT_A                Edad       SexoMasculino 
         56.7407548           2.1889326          -0.1217495           3.0539430 
EtniaBlanco-Mestizo       EtniaIndigena           EtniaRrom 
          2.4116803           3.3097938           3.9354965 </code></pre>
</div>
</div>
<p>y los coeficientes distintos de cero:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>        (Intercept)               LRT_A                Edad       SexoMasculino 
         56.7407548           2.1889326          -0.1217495           3.0539430 
EtniaBlanco-Mestizo       EtniaIndigena           EtniaRrom 
          2.4116803           3.3097938           3.9354965 </code></pre>
</div>
</div>
</section>
<section id="lrt-cinta-métrica-1" class="level3">
<h3 class="anchored" data-anchor-id="lrt-cinta-métrica-1">LRT cinta métrica</h3>
<p>Se particionan los datos en entrenamiento y prueba,</p>
<p>Algunos coeficientes se hacen cero:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelos_files/figure-html/unnamed-chunk-105-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Se hace <strong><em>k-fold cross validation</em></strong> con <span class="math inline">\(k = 10\)</span> y se promedia el MSE:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelos_files/figure-html/unnamed-chunk-106-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 14.70674</code></pre>
</div>
</div>
<p>Los coeficientes del modelo resultante son:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>        (Intercept)              LRT_CM                Edad       SexoMasculino 
         55.1931059           2.1618265          -0.1276708           4.1246462 
EtniaBlanco-Mestizo       EtniaIndigena           EtniaRrom 
          2.0666234           2.7561268           1.0962121 </code></pre>
</div>
</div>
<p>y los coeficientes distintos de cero:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>        (Intercept)              LRT_CM                Edad       SexoMasculino 
         55.1931059           2.1618265          -0.1276708           4.1246462 
EtniaBlanco-Mestizo       EtniaIndigena           EtniaRrom 
          2.0666234           2.7561268           1.0962121 </code></pre>
</div>
</div>
</section>
<section id="lrm-pierna-estirada-1" class="level3">
<h3 class="anchored" data-anchor-id="lrm-pierna-estirada-1">LRM pierna estirada</h3>
<p>Se particionan los datos en entrenamiento y prueba,</p>
<p>Algunos coeficientes se hacen cero:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelos_files/figure-html/unnamed-chunk-110-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Se hace <strong><em>k-fold cross validation</em></strong> con <span class="math inline">\(k = 10\)</span> y se promedia el MSE:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelos_files/figure-html/unnamed-chunk-111-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11.55844</code></pre>
</div>
</div>
<p>Los coeficientes del modelo resultante son:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>        (Intercept)               LRM_R                Edad       SexoMasculino 
         65.5147318           2.2166621          -0.1155642           3.7977231 
EtniaBlanco-Mestizo       EtniaIndigena           EtniaRrom 
          2.5804444           3.5222019           5.3306652 </code></pre>
</div>
</div>
<p>y los coeficientes distintos de cero:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>        (Intercept)               LRM_R                Edad       SexoMasculino 
         65.5147318           2.2166621          -0.1155642           3.7977231 
EtniaBlanco-Mestizo       EtniaIndigena           EtniaRrom 
          2.5804444           3.5222019           5.3306652 </code></pre>
</div>
</div>
</section>
<section id="lrm-pierna-a-90-1" class="level3">
<h3 class="anchored" data-anchor-id="lrm-pierna-a-90-1">LRM pierna a 90°</h3>
<p>Se particionan los datos en entrenamiento y prueba,</p>
<p>Algunos coeficientes se hacen cero:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelos_files/figure-html/unnamed-chunk-115-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Se hace <strong><em>k-fold cross validation</em></strong> con <span class="math inline">\(k = 10\)</span> y se promedia el MSE:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelos_files/figure-html/unnamed-chunk-116-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10.8733</code></pre>
</div>
</div>
<p>Los coeficientes del modelo resultante son:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>        (Intercept)              LRM_90                Edad       SexoMasculino 
         65.5824897           2.2014519          -0.1013947           4.6558848 
EtniaBlanco-Mestizo       EtniaIndigena           EtniaRrom 
          0.1271305           0.0000000           0.1392289 </code></pre>
</div>
</div>
<p>y los coeficientes distintos de cero:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>        (Intercept)              LRM_90                Edad       SexoMasculino 
         65.5824897           2.2014519          -0.1013947           4.6558848 
EtniaBlanco-Mestizo           EtniaRrom 
          0.1271305           0.1392289 </code></pre>
</div>
</div>
</section>
</section>
<section id="modelo-gamma" class="level2">
<h2 class="anchored" data-anchor-id="modelo-gamma">Modelo Gamma</h2>
</section>
<section id="modelo-gamma-1" class="level2">
<h2 class="anchored" data-anchor-id="modelo-gamma-1">Modelo Gamma</h2>
<section id="lrt-antropómetro-2" class="level3">
<h3 class="anchored" data-anchor-id="lrt-antropómetro-2">LRT Antropómetro</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Talla ~ LRT_A + Edad + Etnia + Sexo, family = Gamma(), 
    data = datos)

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)          1.044e-02  1.358e-04  76.905  &lt; 2e-16 ***
LRT_A               -8.823e-05  2.245e-06 -39.291  &lt; 2e-16 ***
Edad                 5.140e-06  8.817e-07   5.830 9.57e-09 ***
EtniaBlanco-Mestizo -1.209e-04  5.954e-05  -2.031   0.0428 *  
EtniaIndigena       -1.696e-04  7.985e-05  -2.123   0.0342 *  
EtniaRrom           -1.767e-04  1.381e-04  -1.280   0.2012    
SexoMasculino       -1.325e-04  1.650e-05  -8.032 6.14e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for Gamma family taken to be 0.0004486863)

    Null deviance: 2.00425  on 542  degrees of freedom
Residual deviance: 0.24156  on 536  degrees of freedom
AIC: 2849.2

Number of Fisher Scoring iterations: 3</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=3986.45
Talla ~ 1

        Df Deviance    AIC
+ LRT_A  1  0.28112 3521.3
+ Sexo   1  0.96443 3706.6
&lt;none&gt;      2.00425 3986.5
+ Etnia  3  1.98665 3987.7
+ Edad   1  2.00387 3988.3

Step:  AIC=2921.58
Talla ~ LRT_A

        Df Deviance    AIC
+ Sexo   1  0.25839 2879.7
+ Edad   1  0.27254 2907.0
&lt;none&gt;      0.28112 2921.6
+ Etnia  3  0.27963 2924.7

Step:  AIC=2877.81
Talla ~ LRT_A + Sexo

        Df Deviance    AIC
+ Edad   1  0.24391 2849.4
&lt;none&gt;      0.25839 2877.8
+ Etnia  3  0.25684 2880.5

Step:  AIC=2848.47
Talla ~ LRT_A + Sexo + Edad

        Df Deviance    AIC
&lt;none&gt;      0.24391 2848.5
+ Etnia  3  0.24156 2849.3</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11.06637</code></pre>
</div>
</div>
</section>
<section id="lrt-cinta-métrica-2" class="level3">
<h3 class="anchored" data-anchor-id="lrt-cinta-métrica-2">LRT cinta métrica</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Talla ~ LRT_CM + Edad + Etnia + Sexo, family = Gamma(), 
    data = datos)

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)          1.051e-02  1.484e-04  70.831  &lt; 2e-16 ***
LRT_CM              -8.717e-05  2.422e-06 -35.988  &lt; 2e-16 ***
Edad                 5.328e-06  9.379e-07   5.680 2.21e-08 ***
EtniaBlanco-Mestizo -1.068e-04  6.342e-05  -1.685   0.0927 .  
EtniaIndigena       -1.448e-04  8.505e-05  -1.703   0.0892 .  
EtniaRrom           -6.135e-05  1.472e-04  -0.417   0.6771    
SexoMasculino       -1.753e-04  1.697e-05 -10.328  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for Gamma family taken to be 0.0005091626)

    Null deviance: 2.00425  on 542  degrees of freedom
Residual deviance: 0.27374  on 536  degrees of freedom
AIC: 2917.1

Number of Fisher Scoring iterations: 3</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=3986.45
Talla ~ 1

         Df Deviance    AIC
+ LRT_CM  1  0.33696 3536.5
+ Sexo    1  0.96443 3706.6
&lt;none&gt;       2.00425 3986.5
+ Etnia   3  1.98665 3987.7
+ Edad    1  2.00387 3988.3

Step:  AIC=3019.97
Talla ~ LRT_CM

        Df Deviance    AIC
+ Sexo   1  0.29131 2948.6
+ Edad   1  0.32934 3009.7
&lt;none&gt;      0.33696 3020.0
+ Etnia  3  0.33599 3024.4

Step:  AIC=2942.91
Talla ~ LRT_CM + Sexo

        Df Deviance    AIC
+ Edad   1  0.27549 2915.5
&lt;none&gt;      0.29131 2942.9
+ Etnia  3  0.29019 2946.8

Step:  AIC=2914.59
Talla ~ LRT_CM + Sexo + Edad

        Df Deviance    AIC
&lt;none&gt;      0.27549 2914.6
+ Etnia  3  0.27374 2917.2</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12.28992</code></pre>
</div>
</div>
</section>
<section id="lrm-pierna-estirada-2" class="level3">
<h3 class="anchored" data-anchor-id="lrm-pierna-estirada-2">LRM pierna estirada</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Talla ~ LRM_R + Edad + Etnia + Sexo, family = Gamma(), 
    data = datos)

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)          1.010e-02  1.459e-04  69.195  &lt; 2e-16 ***
LRM_R               -8.954e-05  2.621e-06 -34.157  &lt; 2e-16 ***
Edad                 4.943e-06  9.752e-07   5.068 5.53e-07 ***
EtniaBlanco-Mestizo -1.320e-04  6.581e-05  -2.005   0.0454 *  
EtniaIndigena       -1.788e-04  8.822e-05  -2.026   0.0432 *  
EtniaRrom           -2.369e-04  1.526e-04  -1.553   0.1211    
SexoMasculino       -1.624e-04  1.797e-05  -9.037  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for Gamma family taken to be 0.0005478053)

    Null deviance: 2.00425  on 542  degrees of freedom
Residual deviance: 0.29489  on 536  degrees of freedom
AIC: 2957.5

Number of Fisher Scoring iterations: 3</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=3986.45
Talla ~ 1

        Df Deviance    AIC
+ LRM_R  1  0.34839 3539.6
+ Sexo   1  0.96443 3706.6
&lt;none&gt;      2.00425 3986.5
+ Etnia  3  1.98665 3987.7
+ Edad   1  2.00387 3988.3

Step:  AIC=3038.09
Talla ~ LRM_R

        Df Deviance    AIC
+ Sexo   1  0.31104 2982.0
+ Edad   1  0.34223 3030.5
&lt;none&gt;      0.34839 3038.1
+ Etnia  3  0.34633 3040.9

Step:  AIC=2978.5
Talla ~ LRM_R + Sexo

        Df Deviance    AIC
+ Edad   1  0.29780 2957.4
&lt;none&gt;      0.31104 2978.5
+ Etnia  3  0.30899 2980.9

Step:  AIC=2956.89
Talla ~ LRM_R + Sexo + Edad

        Df Deviance    AIC
&lt;none&gt;      0.29780 2956.9
+ Etnia  3  0.29489 2957.6</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 13.42149</code></pre>
</div>
</div>
</section>
<section id="lrm-pierna-90" class="level3">
<h3 class="anchored" data-anchor-id="lrm-pierna-90">LRM pierna 90°</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Talla ~ LRM_90 + Edad + Etnia + Sexo, family = Gamma(), 
    data = datos)

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)          1.015e-02  1.488e-04  68.205  &lt; 2e-16 ***
LRM_90              -8.948e-05  2.654e-06 -33.715  &lt; 2e-16 ***
Edad                 4.913e-06  9.837e-07   4.995 7.99e-07 ***
EtniaBlanco-Mestizo -9.842e-05  6.634e-05  -1.483    0.139    
EtniaIndigena       -9.528e-05  8.898e-05  -1.071    0.285    
EtniaRrom           -1.621e-04  1.539e-04  -1.053    0.293    
SexoMasculino       -2.031e-04  1.737e-05 -11.692  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for Gamma family taken to be 0.0005573112)

    Null deviance: 2.00425  on 542  degrees of freedom
Residual deviance: 0.29974  on 536  degrees of freedom
AIC: 2966.4

Number of Fisher Scoring iterations: 3</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=3986.45
Talla ~ 1

         Df Deviance    AIC
+ LRM_90  1  0.38114 3548.4
+ Sexo    1  0.96443 3706.6
&lt;none&gt;       2.00425 3986.5
+ Etnia   3  1.98665 3987.7
+ Edad    1  2.00387 3988.3

Step:  AIC=3086.87
Talla ~ LRM_90

        Df Deviance    AIC
+ Sexo   1  0.31443 2994.1
+ Edad   1  0.37671 3082.6
&lt;none&gt;      0.38114 3086.9
+ Etnia  3  0.38057 3092.1

Step:  AIC=2984.39
Talla ~ LRM_90 + Sexo

        Df Deviance    AIC
+ Edad   1  0.30110 2963.4
&lt;none&gt;      0.31443 2984.4
+ Etnia  3  0.31366 2989.1

Step:  AIC=2962.86
Talla ~ LRM_90 + Sexo + Edad

        Df Deviance    AIC
&lt;none&gt;      0.30110 2962.9
+ Etnia  3  0.29974 2966.4</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 13.47367</code></pre>
</div>
</div>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>